import type { System, ResolvedToken } from '../types.ts';

type Idx = Map<string, ResolvedToken>;

/** W3C Design Tokens Community Group format (2024 draft) with light/dark as $extensions. */
export function dtcg(system: System, idx: Idx): string {
  const out: Record<string, unknown> = { $schema: 'https://tr.designtokens.org/format/', $description: `${system.meta.name} design tokens, generated by canon` };
  const set = (path: string[], value: unknown) => {
    let cur = out as Record<string, unknown>;
    for (const p of path.slice(0, -1)) cur = (cur[p] ??= {}) as Record<string, unknown>;
    cur[path[path.length - 1]] = value;
  };
  const typeOf = (group: string, path: string): string => {
    if (group === 'color') return 'color';
    if (group === 'space' || group === 'radius' || group === 'size' || group === 'breakpoint' || (group === 'font' && path.startsWith('size')) || (group === 'font' && path.startsWith('control')) || (group === 'border')) return 'dimension';
    if (group === 'shadow') return 'shadow';
    if (group === 'font' && path.startsWith('family')) return 'fontFamily';
    if (group === 'font' && path.startsWith('weight')) return 'fontWeight';
    if (group === 'motion' && path.startsWith('duration')) return 'duration';
    if (group === 'motion' && path.startsWith('easing')) return 'cubicBezier';
    if (group === 'z' || group === 'opacity') return 'number';
    return 'string';
  };
  for (const t of idx.values()) {
    if (t.group === 'type') continue;
    const path = t.ref.slice(1, -1).split('.');
    const token: Record<string, unknown> = { $type: typeOf(t.group, t.path), $value: t.light };
    if (t.description) token.$description = t.description;
    if (t.themed) token.$extensions = { 'com.canon.theme': { light: t.light, dark: t.dark }, 'com.canon.cssVar': t.cssVar };
    else token.$extensions = { 'com.canon.cssVar': t.cssVar };
    set(path, token);
  }
  for (const [name, ts] of Object.entries(system.tokens.type)) {
    set(['type', name], {
      $type: 'typography',
      $description: ts.description,
      $value: {
        fontFamily: idx.get(`type.${name}.family`)!.light,
        fontSize: idx.get(`type.${name}.size`)!.light,
        fontWeight: idx.get(`type.${name}.weight`)!.light,
        lineHeight: idx.get(`type.${name}.lineHeight`)!.light,
        letterSpacing: idx.get(`type.${name}.letterSpacing`)!.light,
        ...(ts.transform ? { textTransform: ts.transform } : {}),
      },
    });
  }
  return JSON.stringify(out, null, 2) + '\n';
}

export function generate(system: System, idx: Idx, write: (rel: string, content: string) => void) {
  write('tokens.dtcg.json', dtcg(system, idx));
}
