// Storybook story generation: one story file per component in an adapter's inventory, plus a
// storybook-init bootstrapper. Generated files carry GENERATED_MARK as their first line so
// storyWrites can tell an untouched-by-hand file from one a person has started editing — and
// refuse to clobber the latter.
import { existsSync, readFileSync, realpathSync, unlinkSync } from 'node:fs';
import { join } from 'node:path';
import type { Write } from '../design-files.ts';
import type { Adapter, ComponentInfo, ExecFn, RenderExample } from '../adapters/types.ts';
import { catalogStory, exclusionReason, type CatalogResult } from './story-catalog.ts';

export const GENERATED_MARK = '// @canon-generated — regenerated by `canon build`; edit variants via Canon, write custom stories in another file.';

/** Render one `<Tag ...>...</Tag>` example per line, indented for the `<div>` wrapper below. */
function elementsBlock(examples: RenderExample[]): string {
  return examples.map((example) => `  ${example.jsx}`).join('\n');
}

/**
 * Compound-component composition for stories: when a component's parts follow the
 * Root/Header/Title/Description/Action/Content/Footer convention (Card, Alert, Dialog-like
 * families), the story renders ONE assembled example — the real nested JSX the app would write —
 * instead of a bare root with placeholder text. Mirrors preview-lib's composedMarkup, but emits
 * real component JSX for Storybook (React actually executes here).
 */
const STORY_ROLES = ['Header', 'Title', 'Description', 'Action', 'Content', 'Footer'] as const;

function composedStory(component: ComponentInfo): { jsx: string; imports: string[] } | undefined {
  const parts = component.parts ?? [];
  const styled = new Set(parts.filter((p) => p.classes !== undefined).map((p) => p.name));
  const exported = new Set(parts.map((p) => p.name)); // every part IS an export of the module
  const name = component.exportName;
  const has = (role: string) => exported.has(name + role);
  // Compose when the family exists, regardless of which members carry static classes —
  // Storybook runs the real components, so even dynamic-classed parts render correctly.
  const roles = STORY_ROLES.filter((r) => has(r));
  if (!exported.has(name) || roles.length < 2) return undefined;

  const tag = (suffix: string, children: string) => `<${name}${suffix}>${children}</${name}${suffix}>`;
  // Title/Description/Action belong INSIDE a Header wrapper when the family has one (Card,
  // Dialog, AlertDialog…) — but a family that puts them directly under its root (shadcn's own
  // Alert has no AlertHeader) must still render them, just unwrapped, rather than silently drop
  // them: dropping left `<Alert>` composing to an empty box (no Title/Description ever emitted)
  // even though both parts were real exports.
  const headerChildren = [
    has('Title') ? tag('Title', `${name} title`) : '',
    has('Description') ? tag('Description', 'Supporting description for this component.') : '',
    has('Action') ? tag('Action', 'Action') : '',
  ].filter(Boolean).join('');
  const header = has('Header') ? tag('Header', headerChildren) : headerChildren;
  const body = [
    header,
    has('Content') ? tag('Content', 'Body content — rendered by the real component.') : '',
    has('Footer') ? tag('Footer', 'Footer') : '',
  ].filter(Boolean).join('\n    ');

  const used = [name, ...roles.map((r) => name + r)].filter((n) => styled.has(n) || exported.has(n));

  // Overlay families (Dialog, Drawer, Sheet, AlertDialog…): the root is a stateful Radix provider
  // that renders NOTHING until open, and children belong inside <NameContent>. Detect by shape —
  // an unstyled root with a styled Content part — and emit the real open composition.
  const rootPart = parts.find((p) => p.name === name);
  const isOverlay = has('Content') && (!rootPart || rootPart.classes === undefined);
  if (isOverlay) {
    const inner = [
      header,
      has('Footer') ? tag('Footer', 'Footer') : '',
    ].filter(Boolean).join('\n      ');
    return {
      jsx: `  <${name} defaultOpen>\n    <${name}Content>\n      ${inner || `${name} content`}\n    </${name}Content>\n  </${name}>`,
      imports: used,
    };
  }

  return {
    jsx: `  <${name} style={{ width: 360 }}>\n    ${body}\n  </${name}>`,
    imports: used,
  };
}

/**
 * Every `import { ... } from '...'` line a story needs: the component's own module (always first,
 * and always including `exportName` itself — `Meta.component` binds to it even when the curated
 * JSX never names it directly, e.g. resizable's exportName is `ResizableHandle` but the example is
 * built from `ResizablePanelGroup`/`ResizablePanel`/`ResizableHandle`), plus one deduplicated,
 * path-sorted line per external module a catalog entry pulled in (a sibling ui component like
 * `label`/`button`, or a real package like `recharts`).
 */
function importLines(component: ComponentInfo, ownNames: string[], externals: { path: string; names: string[] }[] | undefined): string[] {
  const own = [...new Set([component.exportName, ...ownNames])];
  const lines = [`import { ${own.join(', ')} } from '${component.importPath}';`];
  const byPath = new Map<string, Set<string>>();
  for (const { path, names } of externals ?? []) {
    const set = byPath.get(path) ?? new Set<string>();
    for (const n of names) set.add(n);
    byPath.set(path, set);
  }
  for (const [path, names] of [...byPath.entries()].sort(([a], [b]) => a.localeCompare(b))) {
    lines.push(`import { ${[...names].join(', ')} } from '${path}';`);
  }
  return lines;
}

/** Build a component's `stories/canon/<slug>.stories.tsx` source. `catalog`, when given (a hit in
 *  the curated catalog — story-catalog.ts), takes priority over the compound/generic paths. */
function storyContent(component: ComponentInfo, examples: RenderExample[], catalog: CatalogResult | undefined): string {
  const { exportName, readOnlyReason } = component;
  // exportName is always a bare PascalCase identifier (see inventory.ts's PASCAL check), so it's
  // always safe to embed directly in a single-quoted title — matching the codebase's quote style.
  const parameters = readOnlyReason
    ? `, parameters: { docs: { description: { component: ${JSON.stringify(`Style block is read-only for Canon: ${readOnlyReason}`)} } } }`
    : '';
  const composed = catalog ? undefined : composedStory(component);
  const imports = catalog
    ? importLines(component, catalog.ownNames, catalog.imports)
    : importLines(component, composed ? [...new Set(composed.imports)].filter((n) => n !== exportName) : [], undefined);
  const renderBody = catalog ? catalog.jsx : (composed ? composed.jsx : elementsBlock(examples));
  return [
    GENERATED_MARK,
    ...imports,
    '',
    // CSF is plain module data. Keep Storybook optional for the app's TypeScript build.
    `const meta = { title: 'Canon/${exportName}', component: ${exportName}${parameters} };`,
    'export default meta;',
    '',
    `export const Variants = { render: () => (<div style={{ display: 'flex', gap: 12, flexWrap: 'wrap', alignItems: 'center' }}>`,
    renderBody,
    `</div>) };`,
    '',
  ].join('\n');
}

/**
 * Build the `Write`s for one Storybook story file per NON-EXCLUDED component (`exclusionReason`,
 * story-catalog.ts — a slug with nothing presentable to show at all, e.g. a bare context provider
 * or a toaster with no static content), under `stories/canon/<slug>.stories.tsx`. Every target is
 * validated before any `Write` is produced (batch semantics): if a target already exists and its
 * content doesn't start with `GENERATED_MARK`, the whole call throws naming that path — nothing is
 * ever silently clobbered, and `installFiles` still gets an all-or-nothing set to apply atomically.
 *
 * For an EXCLUDED slug, a previously generated story file is deleted directly (there's no "delete"
 * in the `Write`/`installFiles` vocabulary) — but only when it still starts with `GENERATED_MARK`;
 * a file a person started hand-editing is never touched, excluded slug or not. This runs only
 * after every non-excluded target has passed its own clobber check, so a batch that's going to
 * fail never deletes anything first.
 */
export function storyWrites(root: string, adapter: Adapter, components: ComponentInfo[]): Write[] {
  root = realpathSync(root); // never trust the caller's path to already be canonical (see inventory.ts)
  const lookup = (slug: string) => components.find((c) => c.slug === slug);

  const included: ComponentInfo[] = [];
  const excludedPaths: string[] = [];
  for (const component of components) {
    const path = join(root, 'stories', 'canon', `${component.slug}.stories.tsx`);
    if (exclusionReason(component, root)) excludedPaths.push(path);
    else included.push(component);
  }

  const targets = included.map((component) => ({
    component,
    path: join(root, 'stories', 'canon', `${component.slug}.stories.tsx`),
  }));

  for (const { path } of targets) {
    if (!existsSync(path)) continue;
    const existing = readFileSync(path, 'utf8');
    if (!existing.startsWith(GENERATED_MARK)) throw new Error(`refusing to overwrite unmarked story: ${path}`);
  }

  for (const path of excludedPaths) {
    if (!existsSync(path)) continue;
    const existing = readFileSync(path, 'utf8');
    if (existing.startsWith(GENERATED_MARK)) unlinkSync(path); // stale cleanup only — never a hand-edited file
  }

  return targets.map(({ component, path }) => {
    const examples = adapter.renderSpec(component);
    const catalog = catalogStory(component, root, lookup);
    const content = storyContent(component, examples, catalog);
    return { root, path, content: Buffer.from(content, 'utf8') };
  });
}

/**
 * Ensure a Storybook install exists at `root`: `'present'` when `<root>/.storybook` already
 * exists, otherwise runs `npx storybook@latest init --yes` through the injected `exec` and
 * reports `'installed'`.
 */
export async function ensureStorybook(root: string, exec: ExecFn): Promise<'present' | 'installed'> {
  if (existsSync(join(root, '.storybook'))) return 'present';
  const result = await exec('npx', ['storybook@latest', 'init', '--yes'], { cwd: root });
  if (result.status !== 0) throw new Error(`stories: storybook init failed (exit ${result.status}): ${result.stderr}`);
  return 'installed';
}
