// Storybook story generation: one story file per component in an adapter's inventory, plus a
// storybook-init bootstrapper. Generated files carry GENERATED_MARK as their first line so
// storyWrites can tell an untouched-by-hand file from one a person has started editing — and
// refuse to clobber the latter.
import { existsSync, readFileSync, realpathSync } from 'node:fs';
import { join } from 'node:path';
import type { Write } from '../design-files.ts';
import type { Adapter, ComponentInfo, ExecFn, RenderExample } from '../adapters/types.ts';

export const GENERATED_MARK = '// @canon-generated — regenerated by `canon build`; edit variants via Canon, write custom stories in another file.';

/** Render one `<Tag ...>...</Tag>` example per line, indented for the `<div>` wrapper below. */
function elementsBlock(examples: RenderExample[]): string {
  return examples.map((example) => `  ${example.jsx}`).join('\n');
}

/** Build a component's `stories/canon/<slug>.stories.tsx` source. */
function storyContent(component: ComponentInfo, examples: RenderExample[]): string {
  const { exportName, importPath, readOnlyReason } = component;
  // exportName is always a bare PascalCase identifier (see inventory.ts's PASCAL check), so it's
  // always safe to embed directly in a single-quoted title — matching the codebase's quote style.
  const parameters = readOnlyReason
    ? `, parameters: { docs: { description: { component: ${JSON.stringify(`Style block is read-only for Canon: ${readOnlyReason}`)} } } }`
    : '';
  return [
    GENERATED_MARK,
    `import type { Meta, StoryObj } from '@storybook/react';`,
    `import { ${exportName} } from '${importPath}';`,
    '',
    `const meta = { title: 'Canon/${exportName}', component: ${exportName}${parameters} } satisfies Meta<typeof ${exportName}>;`,
    'export default meta;',
    'type Story = StoryObj<typeof meta>;',
    '',
    `export const Variants: Story = { render: () => (<div style={{ display: 'flex', gap: 12, flexWrap: 'wrap', alignItems: 'center' }}>`,
    elementsBlock(examples),
    `</div>) };`,
    '',
  ].join('\n');
}

/**
 * Build the `Write`s for one Storybook story file per component, under
 * `stories/canon/<slug>.stories.tsx`. Every target is validated before any `Write` is produced
 * (batch semantics): if a target already exists and its content doesn't start with
 * `GENERATED_MARK`, the whole call throws naming that path — nothing is ever silently clobbered,
 * and `installFiles` still gets an all-or-nothing set to apply atomically.
 */
export function storyWrites(root: string, adapter: Adapter, components: ComponentInfo[]): Write[] {
  root = realpathSync(root); // never trust the caller's path to already be canonical (see inventory.ts)
  const targets = components.map((component) => ({
    component,
    path: join(root, 'stories', 'canon', `${component.slug}.stories.tsx`),
  }));

  for (const { path } of targets) {
    if (!existsSync(path)) continue;
    const existing = readFileSync(path, 'utf8');
    if (!existing.startsWith(GENERATED_MARK)) throw new Error(`refusing to overwrite unmarked story: ${path}`);
  }

  return targets.map(({ component, path }) => {
    const examples = adapter.renderSpec(component);
    const content = storyContent(component, examples);
    return { root, path, content: Buffer.from(content, 'utf8') };
  });
}

/**
 * Ensure a Storybook install exists at `root`: `'present'` when `<root>/.storybook` already
 * exists, otherwise runs `npx storybook@latest init --yes` through the injected `exec` and
 * reports `'installed'`.
 */
export async function ensureStorybook(root: string, exec: ExecFn): Promise<'present' | 'installed'> {
  if (existsSync(join(root, '.storybook'))) return 'present';
  const result = await exec('npx', ['storybook@latest', 'init', '--yes'], { cwd: root });
  if (result.status !== 0) throw new Error(`stories: storybook init failed (exit ${result.status}): ${result.stderr}`);
  return 'installed';
}
