import type { System, ResolvedToken } from '../types.ts';
import { indexTokens, toCssVars } from '../tokens/resolve.ts';

type Idx = Map<string, ResolvedToken>;

/**
 * Tailwind v4 `@theme` file and a v3 preset. Both map utilities onto the CSS
 * variables, so `bg-action` compiles to `background-color: var(--cn-color-bg-action)`
 * and follows the theme automatically. The default Tailwind palette is removed so
 * `bg-blue-500` does not exist — the lint rule and the LLM spec rely on that.
 */
export function tailwindV4(system: System, idx: Idx): string {
  const p = system.meta.prefix;
  const t = system.tokens;
  const variable = (ref: string) => toCssVars(`{${ref}}`, idx);
  const lines: string[] = [];
  lines.push(`/* ${system.meta.name} — Tailwind v4 theme. Generated by canon. Import AFTER tokens.css:`);
  lines.push(`   @import "tailwindcss";`);
  lines.push(`   @import "./${p}.css";      (tokens + base + components)`);
  lines.push(`   @import "./tailwind.theme.css"; */`);
  lines.push(`@theme {`);
  lines.push(`  /* wipe the default palette so only system colors exist */`);
  lines.push(`  --color-*: initial;`);
  lines.push(`  --font-*: initial;`);
  lines.push(`  --shadow-*: initial;`);
  lines.push(`  --radius-*: initial;`);
  lines.push(`  --text-*: initial;`);
  lines.push(`  --breakpoint-*: initial;`);
  for (const [name, val] of Object.entries(t.color.primitive)) {
    if (typeof val === 'string') lines.push(`  --color-${name}: ${variable(name)};`);
    else for (const step of Object.keys(val)) lines.push(`  --color-${name}-${step}: ${variable(`${name}.${step}`)};`);
  }
  for (const name of Object.keys(t.color.semantic)) lines.push(`  --color-${name}: ${variable(`color.${name}`)};`);
  for (const k of Object.keys(t.font.family)) lines.push(`  --font-${k}: ${variable(`font.family.${k}`)};`);
  for (const k of Object.keys(t.font.size)) lines.push(`  --text-${k}: ${variable(`font.size.${k}`)};`);
  for (const k of Object.keys(t.type)) {
    lines.push(`  --text-${k}: ${variable(`type.${k}.size`)};`);
    lines.push(`  --text-${k}--line-height: ${variable(`type.${k}.lineHeight`)};`);
    lines.push(`  --text-${k}--letter-spacing: ${variable(`type.${k}.letterSpacing`)};`);
    lines.push(`  --text-${k}--font-weight: ${variable(`type.${k}.weight`)};`);
  }
  for (const k of Object.keys(t.font.weight)) lines.push(`  --font-weight-${k}: ${variable(`font.weight.${k}`)};`);
  for (const k of Object.keys(t.font.lineHeight)) lines.push(`  --leading-${k}: ${variable(`font.lineHeight.${k}`)};`);
  for (const k of Object.keys(t.font.letterSpacing)) lines.push(`  --tracking-${k}: ${variable(`font.letterSpacing.${k}`)};`);
  lines.push(`  --spacing: 4px;`);
  for (const k of Object.keys(t.radius)) lines.push(`  --radius-${k}: ${variable(`radius.${k}`)};`);
  for (const k of Object.keys(t.shadow)) lines.push(`  --shadow-${k}: ${variable(`shadow.${k}`)};`);
  for (const [k, v] of Object.entries(t.breakpoint)) lines.push(`  --breakpoint-${k}: ${v};`);
  for (const k of Object.keys(t.size.container)) lines.push(`  --container-${k}: ${variable(`size.container.${k}`)};`);
  for (const k of Object.keys(t.size.control)) lines.push(`  --spacing-control-${k}: ${variable(`size.control.${k}`)};`);
  for (const k of Object.keys(t.size.icon)) lines.push(`  --spacing-icon-${k}: ${variable(`size.icon.${k}`)};`);
  for (const k of Object.keys(t.z)) lines.push(`  --z-index-${k}: ${variable(`z.${k}`)};`);
  for (const k of Object.keys(t.motion.duration)) lines.push(`  --duration-${k}: ${variable(`motion.duration.${k}`)};`);
  for (const k of Object.keys(t.motion.easing)) lines.push(`  --ease-${k}: ${variable(`motion.easing.${k}`)};`);
  lines.push(`}`);
  lines.push(`@custom-variant dark (&:where([data-theme="dark"], [data-theme="dark"] *));`);
  return lines.join('\n') + '\n';
}

export function tailwindV3(system: System, idx: Idx = indexTokens(system.tokens, system.meta.prefix)): string {
  const t = system.tokens;
  const variable = (ref: string) => toCssVars(`{${ref}}`, idx);
  const colors: Record<string, unknown> = {};
  for (const [name, val] of Object.entries(t.color.primitive)) {
    if (typeof val === 'string') colors[name] = variable(name);
    else colors[name] = Object.fromEntries(Object.keys(val).map((s) => [s, variable(`${name}.${s}`)]));
  }
  for (const name of Object.keys(t.color.semantic)) colors[name] = variable(`color.${name}`);
  const fontSize: Record<string, unknown> = {};
  for (const k of Object.keys(t.font.size)) fontSize[k] = variable(`font.size.${k}`);
  for (const k of Object.keys(t.type)) fontSize[k] = [variable(`type.${k}.size`), { lineHeight: variable(`type.${k}.lineHeight`), letterSpacing: variable(`type.${k}.letterSpacing`), fontWeight: variable(`type.${k}.weight`) }];
  const preset = {
    darkMode: ['selector', '[data-theme="dark"]'],
    theme: {
      colors,
      fontFamily: Object.fromEntries(Object.keys(t.font.family).map((k) => [k, variable(`font.family.${k}`)])),
      fontSize,
      fontWeight: Object.fromEntries(Object.keys(t.font.weight).map((k) => [k, variable(`font.weight.${k}`)])),
      lineHeight: Object.fromEntries(Object.keys(t.font.lineHeight).map((k) => [k, variable(`font.lineHeight.${k}`)])),
      letterSpacing: Object.fromEntries(Object.keys(t.font.letterSpacing).map((k) => [k, variable(`font.letterSpacing.${k}`)])),
      spacing: Object.fromEntries(Object.keys(t.space).map((k) => [k, variable(`space.${k}`)])),
      borderRadius: Object.fromEntries(Object.keys(t.radius).map((k) => [k, variable(`radius.${k}`)])),
      boxShadow: Object.fromEntries(Object.keys(t.shadow).map((k) => [k, variable(`shadow.${k}`)])),
      screens: t.breakpoint,
      zIndex: Object.fromEntries(Object.keys(t.z).map((k) => [k, variable(`z.${k}`)])),
      transitionDuration: Object.fromEntries(Object.keys(t.motion.duration).map((k) => [k, variable(`motion.duration.${k}`)])),
      transitionTimingFunction: Object.fromEntries(Object.keys(t.motion.easing).map((k) => [k, variable(`motion.easing.${k}`)])),
      extend: { maxWidth: Object.fromEntries(Object.keys(t.size.container).map((k) => [`container-${k}`, variable(`size.container.${k}`)])) },
    },
  };
  return `// ${system.meta.name} — Tailwind v3 preset. Generated by canon.\n// tailwind.config.js: module.exports = { presets: [require('./design/dist/tailwind.preset.cjs')], content: [...] }\n// The default palette is replaced on purpose: only system colors exist.\nmodule.exports = ${JSON.stringify(preset, null, 2)};\n`;
}

export function generate(system: System, idx: Idx, write: (rel: string, content: string) => void) {
  write('tailwind.theme.css', tailwindV4(system, idx));
  write('tailwind.preset.cjs', tailwindV3(system, idx));
}
