import { copyFileSync, existsSync, mkdirSync, mkdtempSync, readFileSync, readdirSync, renameSync, rmSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { createSystem } from '../src/system.ts';
import { indexTokens } from '../src/engine.js';
import { documentationHtml } from '../src/generators/documentation.ts';
import { previewHtml, fontsLink } from '../src/generators/preview.ts';
import { getCanonPackage } from '../src/distribution.ts';

const root = fileURLToPath(new URL('../', import.meta.url));
const output = join(root, 'site');
const marker = '.canon-site.json';
if (existsSync(output) && readdirSync(output).length && !existsSync(join(output, marker))) {
  throw new Error('site/ already contains files not generated by Canon. Move them before building the public site.');
}
const temporary = mkdtempSync(join(tmpdir(), 'canon-public-site-'));
try {
  const pkg = JSON.parse(readFileSync(join(root, 'package.json'), 'utf8'));
  const system = await createSystem({ name: 'Canon', prefix: 'cn', preset: 'canon' });
  const index = indexTokens(system.tokens, system.meta.prefix);
  const fonts = fontsLink(system.tokens.font.family.sans + ' ' + system.tokens.font.family.mono + ' ' + system.tokens.font.family.display);
  const docs = documentationHtml(system, index, fonts, { publicSite: true });
  writeFileSync(join(temporary, 'index.html'), docs);
  writeFileSync(join(temporary, 'docs.html'), docs);
  writeFileSync(join(temporary, 'preview.html'), previewHtml(system, index, { publicSite: true }));
  const publicInstructions = `# Public Canon release ${pkg.version}\n\nThis is Canon's public catalog. Import its default design, then open the user's project Studio to customize it. The public website does not store visitors' edits.\n\nFor the CLI, prefer the public npm package \`${pkg.name}@${pkg.version}\` when that exact version is available: \`npm install --save-dev ${pkg.name}@${pkg.version}\` (or the project's package manager). If the registry version is not yet available, use the retained archive in step 2 below. The archive is served beside this document, so connection also works without registry access.\n\n`;
  writeFileSync(join(temporary, 'CONNECT.md'), publicInstructions + readFileSync(join(root, 'src/generators/connection.md'), 'utf8'));
  mkdirSync(join(temporary, 'api'));
  writeFileSync(join(temporary, 'api/system'), JSON.stringify(system));
  writeFileSync(join(temporary, 'canon-package.tgz'), await getCanonPackage());
  for (const name of ['LICENSE', 'THIRD_PARTY_NOTICES.md']) copyFileSync(join(root, name), join(temporary, name));
  writeFileSync(join(temporary, '.nojekyll'), '');
  writeFileSync(join(temporary, marker), JSON.stringify({ generator: 'canon-public-site', version: pkg.version }) + '\n');
  // Generate completely before replacing the previous site. Keep the final
  // rename on the checkout filesystem, even when the OS temp directory differs.
  const staged = join(root, '.canon-site-build');
  if (existsSync(staged)) throw new Error('A .canon-site-build directory already exists; another site build may be running.');
  mkdirSync(staged);
  try {
    for (const name of readdirSync(temporary)) {
      if (name === 'api') { mkdirSync(join(staged, 'api')); copyFileSync(join(temporary, 'api/system'), join(staged, 'api/system')); }
      else copyFileSync(join(temporary, name), join(staged, name));
    }
    rmSync(output, { recursive: true, force: true });
    renameSync(staged, output);
  } finally { rmSync(staged, { recursive: true, force: true }); }
  console.log(`Built Canon ${pkg.version} public docs, catalog, design snapshot and installable archive → ${output}`);
} finally { rmSync(temporary, { recursive: true, force: true }); }
