// Shared snippets for application page patterns.
import { ICON } from '../components/_shared.ts';
export { ICON };
export const IMG = (ratio = '16 / 9', attrs = '') => `<span class="cn-placeholder" style="aspect-ratio:${ratio}" role="img" aria-label="Placeholder image" ${attrs}><svg viewBox="0 0 160 90" preserveAspectRatio="none" aria-hidden="true"><rect width="160" height="90" fill="var(--cn-color-bg-muted)"/><path d="M0 90L160 0" stroke="var(--cn-color-border-strong)" stroke-width="1"/></svg></span>`;
export const BTN = (variant: string, label: string, size = 'md', icon = '') => `<button type="button" class="cn-button" data-variant="${variant}" data-size="${size}">${icon ? icon.replace('cn-icon', 'cn-button__icon') : ''}<span class="cn-button__label">${label}</span></button>`;
export const AVATAR = (i: string, n: string, size = 'md', tone = 'neutral', status = 'none') => `<span class="cn-avatar" data-size="${size}" data-shape="circle" data-tone="${tone}" data-status="${status}" role="img" aria-label="${n}"><span class="cn-avatar__fallback" aria-hidden="true">${i}</span>${status !== 'none' ? '<span class="cn-avatar__status"></span>' : ''}</span>`;
export const BADGE = (text: string, tone = 'neutral', variant = 'soft', dot = false) => `<span class="cn-badge" data-tone="${tone}" data-variant="${variant}" data-size="sm">${dot ? '<span class="cn-badge__dot"></span>' : ''}${text}</span>`;
const navItem = (label: string, icon: string, current = false, badge = '') => `<a href="#" class="cn-sidebar__item"${current ? ' aria-current="page"' : ''}>${icon.replace('cn-icon', 'cn-sidebar__icon')}<span class="cn-sidebar__label">${label}</span>${badge ? `<span class="cn-sidebar__badge">${badge}</span>` : ''}</a>`;
export const SIDEBAR = (current = 'Dashboard', variant = 'simple', theme = 'light') => `<nav class="cn-sidebar" data-variant="${variant}" data-theme="${theme}" aria-label="Main"><div class="cn-sidebar__brand"><span class="cn-sidebar__logo" aria-hidden="true"></span><span class="cn-sidebar__brand-name">Lumen</span></div>${variant === 'slim' ? '' : `<div class="cn-sidebar__search cn-input" data-variant="default" data-size="md">${ICON.search.replace('cn-icon', 'cn-input__icon')}<input class="cn-input__field" type="search" placeholder="Search" aria-label="Search"></div>`}<div class="cn-sidebar__nav">${navItem('Home', ICON.home, current === 'Home')}${navItem('Dashboard', ICON.calendar, current === 'Dashboard')}${navItem('Projects', ICON.copy, current === 'Projects')}${navItem('Tasks', ICON.check, current === 'Tasks', '10')}${navItem('Reporting', ICON.inbox, current === 'Reporting')}${navItem('Users', ICON.user, current === 'Users')}</div><div class="cn-sidebar__footer">${navItem('Support', ICON.info)}${navItem('Settings', ICON.settings, current === 'Settings')}<div class="cn-sidebar__account"><span class="cn-sidebar__avatar" aria-hidden="true">MC</span><div class="cn-sidebar__account-text"><span class="cn-sidebar__name">Maya Chen</span><span class="cn-sidebar__email">maya@lumen.co</span></div><button type="button" class="cn-sidebar__account-action" aria-label="Log out">${ICON.external}</button></div></div></nav>`;
export const PAGE_HEADER = (title: string, desc: string, actions: string, variant = 'simple', extra = '') => `<header class="cn-page-header" data-variant="${variant}" data-divider="yes">${extra}<div class="cn-page-header__content"><h1 class="cn-page-header__title">${title}</h1><p class="cn-page-header__description">${desc}</p></div><div class="cn-page-header__actions">${actions}</div></header>`;
export const TABS = (items: string[], active = 0, variant = 'underline') => `<div class="cn-tabs" data-variant="${variant}" data-size="md" role="tablist">${items.map((t, i) => `<button type="button" class="cn-tabs__tab" role="tab" aria-selected="${i === active}">${t}</button>`).join('')}</div>`;
export const STAT = (label: string, value: string, delta: string, trend: 'up' | 'down' | 'flat' = 'up', desc = 'vs last month') => `<div class="cn-stat" data-size="md" data-variant="card" data-trend="${trend}"><div class="cn-stat__label">${label}</div><div class="cn-stat__value">${value}</div><div class="cn-stat__delta"><svg class="cn-stat__icon" viewBox="0 0 16 16" fill="none" stroke="currentColor" stroke-width="1.75" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="${trend === 'down' ? 'M8 3v10M4 9l4 4 4-4' : trend === 'flat' ? 'M3 8h10' : 'M8 13V3M4 7l4-4 4 4'}"/></svg><span>${delta}</span></div><div class="cn-stat__description">${desc}</div></div>`;
export const CHART = (h = 240) => `<svg class="cn-app__chart" viewBox="0 0 800 ${h}" preserveAspectRatio="none" role="img" aria-label="Line chart placeholder"><g class="cn-app__grid">${[0.2, 0.4, 0.6, 0.8].map((f) => `<line x1="0" x2="800" y1="${h * f}" y2="${h * f}"/>`).join('')}</g><path class="cn-app__area" d="M0 ${h * 0.75} C100 ${h * 0.7} 150 ${h * 0.5} 240 ${h * 0.55} S400 ${h * 0.3} 480 ${h * 0.35} S640 ${h * 0.15} 800 ${h * 0.2} V${h} H0 Z"/><path class="cn-app__line" d="M0 ${h * 0.75} C100 ${h * 0.7} 150 ${h * 0.5} 240 ${h * 0.55} S400 ${h * 0.3} 480 ${h * 0.35} S640 ${h * 0.15} 800 ${h * 0.2}"/></svg>`;
export const BARS = (h = 240) => `<svg class="cn-app__chart" viewBox="0 0 800 ${h}" preserveAspectRatio="none" role="img" aria-label="Bar chart placeholder"><g class="cn-app__grid">${[0.25, 0.5, 0.75].map((f) => `<line x1="0" x2="800" y1="${h * f}" y2="${h * f}"/>`).join('')}</g>${[0.4, 0.55, 0.35, 0.7, 0.6, 0.8, 0.5, 0.9, 0.65, 0.75, 0.55, 0.85].map((v, i) => `<rect class="cn-app__bar" x="${i * 66 + 14}" width="40" y="${h - h * v}" height="${h * v}" rx="4"/>`).join('')}</svg>`;
export const CARD = (header: string, body: string, footer = '') => `<section class="cn-card" data-variant="default" data-padding="none">${header ? `<div class="cn-section-header" data-variant="card" data-divider="yes">${header}</div>` : ''}<div class="cn-card__body cn-app__card-body">${body}</div>${footer ? `<footer class="cn-card__footer">${footer}</footer>` : ''}</section>`;
export const CARD_HEAD = (title: string, desc = '', actions = '', badge = '') => `<div class="cn-section-header__content"><h2 class="cn-section-header__title">${title}${badge ? ` <span class="cn-section-header__badge">${badge}</span>` : ''}</h2>${desc ? `<p class="cn-section-header__description">${desc}</p>` : ''}</div>${actions ? `<div class="cn-section-header__actions">${actions}</div>` : ''}`;
export const PEOPLE = [['MC', 'Maya Chen', 'maya@lumen.co', 'Product Manager', 'accent'], ['DC', 'Daniel Costa', 'daniel@lumen.co', 'Engineering', 'success'], ['SA', 'Sofia Almeida', 'sofia@lumen.co', 'Design', 'warning'], ['LF', 'Lucas Ferreira', 'lucas@lumen.co', 'Frontend', 'info'], ['AK', 'Aisha Khan', 'aisha@lumen.co', 'Backend', 'accent'], ['NB', 'Noah Berg', 'noah@lumen.co', 'Product Design', 'success']];
export const CHECKBOX = (label = '', checked = false) => `<label class="cn-checkbox" data-size="sm"><input class="cn-checkbox__input" type="checkbox"${checked ? ' checked' : ''} aria-label="${label || 'Select row'}"><span class="cn-checkbox__control" aria-hidden="true"><svg class="cn-checkbox__indicator" viewBox="0 0 16 16" fill="none" stroke="currentColor" stroke-width="1.75" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="M3 8.5l3 3 7-7"/></svg></span>${label ? `<span class="cn-checkbox__label">${label}</span>` : ''}</label>`;
export const TEAM_TABLE = (rows = PEOPLE, selectable = true) => `<table class="cn-table" data-density="default" data-variant="default" data-interactive><thead class="cn-table__head"><tr class="cn-table__row">${selectable ? `<th class="cn-table__header-cell" scope="col" style="width:48px">${CHECKBOX()}</th>` : ''}<th class="cn-table__header-cell" scope="col">Name</th><th class="cn-table__header-cell" scope="col">Status</th><th class="cn-table__header-cell" scope="col">Role</th><th class="cn-table__header-cell" scope="col">Email address</th><th class="cn-table__header-cell" scope="col">Teams</th><th class="cn-table__header-cell" scope="col"><span class="cn-sr-only">Actions</span></th></tr></thead><tbody class="cn-table__body">${rows.map(([i, n, e, r, t], k) => `<tr class="cn-table__row"${k === 1 ? ' data-selected' : ''}>${selectable ? `<td class="cn-table__cell">${CHECKBOX('', k === 1)}</td>` : ''}<td class="cn-table__cell"><div class="cn-row" data-gap="3">${AVATAR(i, n, 'sm', t)}<div class="cn-stack" data-gap="0"><span class="cn-text-label-sm">${n}</span><span class="cn-text-body-sm cn-app__muted">@${n.split(' ')[0].toLowerCase()}</span></div></div></td><td class="cn-table__cell">${BADGE(k % 3 === 2 ? 'Offline' : 'Active', k % 3 === 2 ? 'neutral' : 'success', 'soft', true)}</td><td class="cn-table__cell">${r}</td><td class="cn-table__cell">${e}</td><td class="cn-table__cell"><div class="cn-row" data-gap="1">${BADGE('Design', 'accent')}${BADGE('Product', 'info')}${k % 2 ? BADGE('+2') : ''}</div></td><td class="cn-table__cell cn-table__actions"><div class="cn-row" data-gap="1" data-justify="end">${BTN('ghost', 'Delete', 'sm')}${BTN('link-color', 'Edit', 'sm')}</div></td></tr>`).join('')}</tbody></table>`;
export const PAGINATION = `<div class="cn-row" data-justify="between" data-gap="3"><span class="cn-text-body-sm cn-app__muted">Page 1 of 10</span><div class="cn-row" data-gap="2">${BTN('outline', 'Previous', 'sm')}${BTN('outline', 'Next', 'sm')}</div></div>`;
export const FIELD = (id: string, label: string, control: string, helper = '', layout = 'vertical') => `<div class="cn-field" data-layout="${layout}" data-size="md"><label class="cn-field__label" for="${id}">${label}</label><div class="cn-field__control">${control}</div>${helper ? `<p class="cn-field__helper">${helper}</p>` : ''}</div>`;
export const INPUT = (id: string, value = '', type = 'text', placeholder = '', icon = '') => `<div class="cn-input" data-variant="default" data-size="md">${icon ? icon.replace('cn-icon', 'cn-input__icon') : ''}<input class="cn-input__field" id="${id}" type="${type}"${value ? ` value="${value}"` : ''}${placeholder ? ` placeholder="${placeholder}"` : ''}></div>`;
export const APP_CSS = `
.cn-app { display: flex; min-height: 100vh; background-color: {color.bg-canvas}; }
.cn-app__main { flex: 1 1 auto; min-width: 0; padding: {space.8}; display: flex; flex-direction: column; gap: {space.8}; }
.cn-app__muted { color: {color.fg-muted}; }
.cn-card[data-padding="none"] > .cn-app__card-body { padding: {space.6}; }
.cn-card[data-padding="none"] > .cn-app__card-body--flush { padding: 0; overflow-x: auto; }
.cn-app__chart { width: 100%; height: auto; display: block; }
.cn-app__grid line { stroke: {color.border-subtle}; stroke-width: 1; }
.cn-app__line { fill: none; stroke: {color.bg-action}; stroke-width: 2; }
.cn-app__area { fill: {color.bg-action-subtle}; }
.cn-app__bar { fill: {color.bg-action}; }
.cn-app__bar:nth-child(even) { fill: {brand.300}; }
.cn-app__table-card .cn-table { width: 100%; }
.cn-app__table-card[data-padding="none"] > .cn-card__footer { padding: {space.3} {space.6}; }
.cn-app__table-card > .cn-card__footer > .cn-row { flex-wrap: wrap; }
.cn-app__legend { display: flex; gap: {space.4}; font-size: {font.size.sm}; color: {color.fg-muted}; }
.cn-app__legend span::before { content: ""; display: inline-block; width: 8px; height: 8px; border-radius: 2px; background-color: {color.bg-action}; margin-inline-end: {space.2}; }
.cn-app__legend span:nth-child(2)::before { background-color: {brand.300}; }
.cn-app__drawer { width: 440px; flex-shrink: 0; border-inline-start: {border.width.thin} solid {color.border-default}; background-color: {color.bg-surface}; display: flex; flex-direction: column; }
.cn-app__drawer-head { display: flex; align-items: flex-start; justify-content: space-between; gap: {space.4}; padding: {space.6}; border-bottom: {border.width.thin} solid {color.border-default}; }
.cn-app__drawer-body { padding: {space.6}; display: flex; flex-direction: column; gap: {space.6}; flex: 1 1 auto; }
.cn-app__drawer-foot { display: flex; justify-content: flex-end; gap: {space.3}; padding: {space.4} {space.6}; border-top: {border.width.thin} solid {color.border-default}; }
.cn-app__dl { display: grid; grid-template-columns: 1fr; gap: {space.4}; }
.cn-app__dl dt { font-size: {font.size.sm}; font-weight: {font.weight.medium}; color: {color.fg-muted}; }
.cn-app__dl dd { font-size: {font.size.sm}; color: {color.fg-default}; margin-top: {space.1}; }
.cn-app__form-row { display: grid; grid-template-columns: 280px 1fr; gap: {space.8}; padding-block: {space.5}; border-bottom: {border.width.thin} solid {color.border-default}; }
.cn-app__form-row > .cn-stack { max-width: 512px; }
.cn-app__form-label { display: flex; flex-direction: column; gap: {space.1}; }
.cn-app__form-label span:first-child { font-size: {font.size.sm}; font-weight: {font.weight.semibold}; color: {color.fg-default}; }
.cn-app__form-label span:last-child { font-size: {font.size.sm}; color: {color.fg-muted}; }
.cn-app__form-actions { display: flex; justify-content: flex-end; gap: {space.3}; padding-top: {space.5}; }
.cn-app__plan { display: flex; flex-direction: column; gap: {space.4}; }
@media (max-width: {breakpoint.lg}) { .cn-app .cn-sidebar { display: none; } .cn-app__drawer { display: none; } .cn-app__form-row { grid-template-columns: 1fr; gap: {space.3}; } }
@media (max-width: {breakpoint.md}) { .cn-app__main { padding: {space.4}; gap: {space.6}; } }`;
