import type { Pattern } from '../types.ts';
import { SIDEBAR, PAGE_HEADER, BTN, AVATAR, BADGE, ICON, APP_CSS, PAGINATION, CARD_HEAD } from './_app.ts';

const ROWS = [['MC', 'Maya Chen', 'accent', 'updated', 'Billing settings', 'Changed payment method to Visa •••• 4242', 'Today 09:41', 'settings', true], ['DC', 'Daniel Costa', 'success', 'deployed', 'Billing webhook v2', 'Production · 2 migrations', 'Today 08:20', 'deploy', false], ['System', 'System', 'neutral', 'rotated', 'API key lum_live_…8f2a', 'Scheduled rotation (90 days)', 'Today 03:00', 'security', false], ['SA', 'Sofia Almeida', 'warning', 'shared', 'Brand assets v3', 'With 8 people · view only', 'Yesterday 18:40', 'files', false], ['AK', 'Aisha Khan', 'accent', 'changed role', 'Elena Rossi', 'Member → Admin', 'Yesterday 16:12', 'members', true], ['LF', 'Lucas Ferreira', 'info', 'exported', 'Customers (2,420 rows)', 'CSV · 1.2 MB', 'Mon 11:05', 'data', false], ['NB', 'Noah Berg', 'success', 'signed in', 'New device', 'MacBook Pro · São Paulo', 'Mon 09:02', 'security', false]];
const CAT: Record<string, string> = { settings: 'neutral', deploy: 'info', security: 'warning', files: 'accent', members: 'accent', data: 'neutral' };
const FILTERS = `<div class="cn-row" data-justify="between" data-gap="3" data-wrap><div class="cn-row" data-gap="3" data-wrap><div class="cn-input" data-variant="default" data-size="md" style="width:280px">${ICON.search.replace('cn-icon', 'cn-input__icon')}<input class="cn-input__field" type="search" placeholder="Search events" aria-label="Search events"></div>${BTN('outline', 'Actor', 'md', ICON.chevronDown)}${BTN('outline', 'Category', 'md', ICON.chevronDown)}${BTN('outline', 'Last 7 days', 'md', ICON.calendar)}</div><div class="cn-row" data-gap="2"><span class="cn-text-body-sm cn-app__muted">1,204 events</span>${BTN('outline', 'Export', 'md', ICON.external)}</div></div>`;

export const auditLog: Pattern = {
  name: 'Audit log and activity',
  slug: 'audit-log',
  category: 'app-page',
  description: 'A chronological record of who did what: a dense table with actor, action, target and metadata and expandable detail rows; a timeline view; and a security-events variant with severity.',
  rules: [
    'Filters: search, actor, category and a date range on the left; count and Export on the right. Filters never hide the table.',
    'Rows are compact (48px): actor (avatar xs + name), action in plain words, target in label-sm, a category badge, timestamp right-aligned in body-sm muted; important rows can expand to a detail block (key/value list) below the row.',
    'Timeline variant groups by day with a vertical line and dots; the same fields, more room for descriptions.',
    'Security events use severity badges (danger/warning/neutral) and a “Review” action; never color entire rows.',
  ],
  html: `<div class="cn-app">${SIDEBAR('Reporting')}<main class="cn-app__main">${PAGE_HEADER('Audit log', 'Every change in your workspace, kept for 400 days.', BTN('outline', 'Retention settings', 'md', ICON.settings))}${FILTERS}<section class="cn-card cn-app__table-card" data-variant="default" data-padding="none"><div class="cn-card__body cn-app__card-body cn-app__card-body--flush" role="region" tabindex="0" aria-label="Scrollable table"><table class="cn-table" data-density="compact" data-variant="default" data-interactive><thead class="cn-table__head"><tr class="cn-table__row"><th class="cn-table__header-cell" scope="col" style="width:32px"></th><th class="cn-table__header-cell" scope="col">Actor</th><th class="cn-table__header-cell" scope="col">Event</th><th class="cn-table__header-cell" scope="col">Category</th><th class="cn-table__header-cell" scope="col" data-align="right">When</th></tr></thead><tbody class="cn-table__body">${ROWS.map(([i, n, tone, a, t, d, w, cat, open]) => `<tr class="cn-table__row"${open ? ' data-selected' : ''}><td class="cn-table__cell"><button type="button" class="cn-audit__toggle" aria-expanded="${open}" aria-label="Details">${ICON.chevronRight}</button></td><td class="cn-table__cell"><div class="cn-row" data-gap="2">${n === 'System' ? `<span class="cn-audit__sys" aria-hidden="true">${ICON.settings}</span>` : AVATAR(i as string, n as string, 'xs', tone as string)}<span class="cn-text-label-sm">${n}</span></div></td><td class="cn-table__cell"><span class="cn-app__muted">${a}</span> <span class="cn-text-label-sm">${t}</span> <span class="cn-app__muted">· ${d}</span></td><td class="cn-table__cell">${BADGE(cat as string, CAT[cat as string])}</td><td class="cn-table__cell" data-align="right">${w}</td></tr>${open ? `<tr class="cn-table__row cn-audit__detail"><td class="cn-table__cell" colspan="5"><dl class="cn-audit__dl"><div><dt>Event ID</dt><dd><code class="cn-code" data-variant="inline" data-size="sm">evt_01J8Z3K2QWERTY</code></dd></div><div><dt>IP address</dt><dd>187.34.12.9 · Florianópolis, BR</dd></div><div><dt>User agent</dt><dd>Chrome 129 · macOS</dd></div><div><dt>Before → After</dt><dd>Mastercard •••• 0913 → Visa •••• 4242</dd></div></dl></td></tr>` : ''}`).join('')}</tbody></table></div><footer class="cn-card__footer">${PAGINATION}</footer></section></main></div>`,
  variants: [
    { title: 'Timeline view', html: `<div class="cn-app">${SIDEBAR('Reporting')}<main class="cn-app__main">${PAGE_HEADER('Activity', 'What your team did this week.', BTN('outline', 'Export', 'md', ICON.external))}${FILTERS}<div class="cn-stack" data-gap="8" style="max-width:800px">${[['Today', ROWS.slice(0, 3)], ['Yesterday', ROWS.slice(3, 5)], ['Monday', ROWS.slice(5)]].map(([day, rows]) => `<section class="cn-stack" data-gap="3"><h2 class="cn-text-label-sm cn-app__muted">${day}</h2><ol class="cn-audit__timeline">${(rows as typeof ROWS).map(([i, n, tone, a, t, d, w, cat]) => `<li class="cn-audit__event"><span class="cn-audit__dot" data-tone="${CAT[cat as string]}" aria-hidden="true"></span><div class="cn-stack" data-gap="1"><div class="cn-row" data-gap="2" data-wrap>${n === 'System' ? '' : AVATAR(i as string, n as string, 'xs', tone as string)}<span class="cn-text-body-sm"><strong>${n}</strong> ${a} <strong>${t}</strong></span>${BADGE(cat as string, CAT[cat as string])}<span class="cn-text-body-xs cn-app__muted">${(w as string).replace('Today ', '').replace('Yesterday ', '').replace('Mon ', '')}</span></div><span class="cn-text-body-sm cn-app__muted">${d}</span></div></li>`).join('')}</ol></section>`).join('')}</div></main></div>` },
    { title: 'Security events with severity', html: `<div class="cn-app">${SIDEBAR('Settings')}<main class="cn-app__main">${PAGE_HEADER('Security events', 'Sign-ins, key rotations and permission changes.', `${BTN('outline', 'Configure alerts', 'md', ICON.settings)}${BTN('primary', 'Review all', 'md')}`)}<div class="cn-grid" data-cols="3" data-gap="6" data-keep>${[['Needs review', '3', 'danger'], ['New devices (7d)', '12', 'warning'], ['Key rotations (30d)', '4', 'neutral']].map(([l, v, tone]) => `<div class="cn-stat" data-size="md" data-variant="card" data-trend="flat"><div class="cn-stat__label">${l}</div><div class="cn-row" data-gap="3" data-align="end"><div class="cn-stat__value">${v}</div>${BADGE(tone === 'danger' ? 'Action needed' : tone === 'warning' ? 'Monitor' : 'Normal', tone as string)}</div></div>`).join('')}</div>${FILTERS.replace('Search events', 'Search security events')}<section class="cn-card cn-app__table-card" data-variant="default" data-padding="none"><div class="cn-section-header" data-variant="card" data-divider="yes">${CARD_HEAD('Events', '', '', BADGE('3 need review', 'danger'))}</div><div class="cn-card__body cn-app__card-body cn-app__card-body--flush" role="region" tabindex="0" aria-label="Scrollable table"><table class="cn-table" data-density="compact" data-variant="default"><thead class="cn-table__head"><tr class="cn-table__row"><th class="cn-table__header-cell" scope="col">Severity</th><th class="cn-table__header-cell" scope="col">Event</th><th class="cn-table__header-cell" scope="col">Actor</th><th class="cn-table__header-cell" scope="col" data-align="right">When</th><th class="cn-table__header-cell" scope="col"><span class="cn-sr-only">Actions</span></th></tr></thead><tbody class="cn-table__body">${[['High', 'danger', 'Sign-in from new country', 'Noah Berg · Lagos, NG', 'NB', 'success', '09:02'], ['High', 'danger', 'Role changed to Admin', 'Elena Rossi by Aisha Khan', 'AK', 'accent', 'Yesterday'], ['Medium', 'warning', 'API key created', 'lum_live_…c91d by Daniel Costa', 'DC', 'success', 'Mon'], ['Low', 'neutral', 'Scheduled key rotation', 'lum_live_…8f2a', 'S', 'neutral', 'Mon'], ['Low', 'neutral', 'Password changed', 'Sofia Almeida', 'SA', 'warning', 'Sun']].map(([sev, tone, ev, who, i, atone, w]) => `<tr class="cn-table__row"><td class="cn-table__cell">${BADGE(sev, tone, 'soft', true)}</td><td class="cn-table__cell"><span class="cn-text-label-sm">${ev}</span></td><td class="cn-table__cell"><div class="cn-row" data-gap="2">${AVATAR(i, who, 'xs', atone)}<span>${who}</span></div></td><td class="cn-table__cell" data-align="right">${w}</td><td class="cn-table__cell cn-table__actions">${tone === 'danger' ? BTN('outline', 'Review', 'sm') : BTN('ghost', 'Details', 'sm')}</td></tr>`).join('')}</tbody></table></div></section></main></div>` },
  ],
  css: `${APP_CSS}
.cn-audit__toggle { appearance: none; border: 0; background: none; padding: 0; width: 24px; height: 24px; border-radius: {radius.sm}; color: {color.fg-subtle}; cursor: pointer; display: inline-flex; align-items: center; justify-content: center; }
.cn-audit__toggle[aria-expanded="true"] { transform: rotate(90deg); }
.cn-audit__toggle .cn-icon { width: 16px; height: 16px; }
.cn-audit__sys { display: inline-flex; align-items: center; justify-content: center; width: 24px; height: 24px; border-radius: {radius.full}; background-color: {color.bg-subtle}; color: {color.fg-subtle}; }
.cn-audit__sys .cn-icon { width: 14px; height: 14px; }
.cn-audit__detail .cn-table__cell { background-color: {color.bg-subtle}; padding-inline-start: 56px; }
.cn-audit__dl { display: grid; grid-template-columns: repeat(4, minmax(0, 1fr)); gap: {space.4}; margin: 0; }
.cn-audit__dl dt { font-size: {font.size.xs}; font-weight: {font.weight.medium}; color: {color.fg-subtle}; }
.cn-audit__dl dd { font-size: {font.size.sm}; color: {color.fg-default}; margin-top: {space.1}; }
.cn-audit__timeline { list-style: none; margin: 0; padding: 0 0 0 {space.6}; position: relative; display: flex; flex-direction: column; gap: {space.5}; border-inline-start: {border.width.thin} solid {color.border-default}; margin-inline-start: 6px; }
.cn-audit__event { position: relative; }
.cn-audit__dot { position: absolute; left: calc({space.6} * -1 - 6px); top: 4px; width: 11px; height: 11px; border-radius: {radius.full}; background-color: {color.border-strong}; box-shadow: 0 0 0 2px {color.bg-canvas}; }
.cn-audit__dot[data-tone="accent"] { background-color: {color.bg-action}; } .cn-audit__dot[data-tone="info"] { background-color: {color.bg-info}; } .cn-audit__dot[data-tone="warning"] { background-color: {color.bg-warning}; }
@media (max-width: {breakpoint.md}) { .cn-audit__dl { grid-template-columns: 1fr 1fr; } }`,
  viewport: 'desktop',
};
