import type { Pattern } from '../types.ts';
import { SIDEBAR, PAGE_HEADER, BTN, TABS, BADGE, ICON, APP_CSS, CARD, CARD_HEAD, FIELD, INPUT } from './_app.ts';

const PLAN = `<section class="cn-card" data-variant="default" data-padding="none"><div class="cn-section-header" data-variant="card" data-divider="yes">${CARD_HEAD('Business plan', 'Renews on 12 October 2026', `${BTN('outline', 'Change plan', 'sm')}`, BADGE('Monthly', 'accent'))}</div><div class="cn-card__body cn-app__card-body cn-stack" data-gap="4"><div class="cn-row" data-justify="between" data-align="end"><span class="cn-text-heading-lg">$20<span class="cn-text-body-md cn-app__muted"> per user / month</span></span><span class="cn-text-body-sm cn-app__muted">14 of 20 seats used</span></div><div class="cn-progress" data-size="sm" data-tone="action" role="progressbar" aria-valuenow="70" aria-valuemin="0" aria-valuemax="100" aria-label="Seats used"><div class="cn-progress__track"><div class="cn-progress__indicator" style="width:70%"></div></div></div></div></section>`;
const PAYMENT = `<section class="cn-card" data-variant="default" data-padding="none"><div class="cn-section-header" data-variant="card" data-divider="yes">${CARD_HEAD('Payment method', 'Change how you pay for your plan.', BTN('outline', 'Edit', 'sm'))}</div><div class="cn-card__body cn-app__card-body"><div class="cn-billing__card"><span class="cn-billing__brand" aria-hidden="true">VISA</span><div class="cn-stack cn-flex-1" data-gap="0"><span class="cn-text-label-sm">Visa ending in 4242</span><span class="cn-text-body-sm cn-app__muted">Expiry 06/2028 · billing@lumen.co</span></div>${BADGE('Default', 'neutral')}</div></div></section>`;
const INVOICES = `<section class="cn-card cn-app__table-card" data-variant="default" data-padding="none"><div class="cn-section-header" data-variant="card" data-divider="yes">${CARD_HEAD('Billing history', 'Download invoices for your records.', BTN('outline', 'Download all', 'sm', ICON.external))}</div><div class="cn-card__body cn-app__card-body cn-app__card-body--flush" role="region" tabindex="0" aria-label="Scrollable table"><table class="cn-table" data-density="default" data-variant="default"><thead class="cn-table__head"><tr class="cn-table__row"><th class="cn-table__header-cell" scope="col">Invoice</th><th class="cn-table__header-cell" scope="col">Date</th><th class="cn-table__header-cell" scope="col">Status</th><th class="cn-table__header-cell" scope="col" data-align="right">Amount</th><th class="cn-table__header-cell" scope="col" data-align="right">Seats</th><th class="cn-table__header-cell" scope="col"><span class="cn-sr-only">Actions</span></th></tr></thead><tbody class="cn-table__body">${[['Sep 2026', 'Paid', 'success', '$280.00', 14], ['Aug 2026', 'Paid', 'success', '$260.00', 13], ['Jul 2026', 'Paid', 'success', '$240.00', 12], ['Jun 2026', 'Refunded', 'neutral', '$220.00', 11], ['May 2026', 'Failed', 'danger', '$220.00', 11]].map(([m, s, tone, a, n], i) => `<tr class="cn-table__row"><td class="cn-table__cell"><span class="cn-text-label-sm">Invoice #${2091 - i}</span></td><td class="cn-table__cell">${m}</td><td class="cn-table__cell">${BADGE(s as string, tone as string, 'soft', true)}</td><td class="cn-table__cell" data-align="right">${a}</td><td class="cn-table__cell" data-align="right">${n}</td><td class="cn-table__cell cn-table__actions">${BTN('link-color', 'Download', 'sm')}</td></tr>`).join('')}</tbody></table></div></section>`;

export const billingPage: Pattern = {
  name: 'Billing and checkout',
  slug: 'billing-page',
  category: 'app-page',
  description: 'Plan and usage, payment method, billing history; a plan change with a comparison; and a checkout form with an order summary.',
  rules: [
    'Billing page: plan card (name, renewal, price per seat, seat usage bar), payment method card (brand mark, last 4, expiry, Default badge), invoices table (number, date, status badge, amount right-aligned, download link).',
    'Failed payments show a danger Alert at the top with a single "Update payment method" action.',
    'Checkout: two columns — form (contact, card number with brand icon, expiry + CVC in a row, country) on the left, an order summary card on the right (line items, subtotal, tax, total in heading-md); the primary button names the amount ("Pay $280.00").',
    'Never mask everything: show the last 4 digits and the brand; never ask for the CVC outside the payment step.',
  ],
  html: `<div class="cn-app">${SIDEBAR('Settings')}<main class="cn-app__main">${PAGE_HEADER('Billing', 'Manage your plan, payment method and invoices.', BTN('outline', 'Contact billing support', 'md'))}${TABS(['Plan', 'Usage', 'Invoices', 'Tax'], 0)}<div class="cn-alert" data-tone="danger" data-variant="soft" data-layout="inline" role="alert"><span class="cn-alert__icon" aria-hidden="true">${ICON.warning}</span><div class="cn-alert__content"><div class="cn-alert__title">Your last payment failed</div><p class="cn-alert__description">We couldn’t charge the Visa ending in 4242 on 12 September. Update your payment method to keep your plan active.</p><div class="cn-alert__actions">${BTN('link-color', 'Update payment method', 'sm')}</div></div></div><div class="cn-grid" data-cols="2" data-gap="6">${PLAN}${PAYMENT}</div>${INVOICES}</main></div>`,
  variants: [
    { title: 'Change plan', html: `<div class="cn-app">${SIDEBAR('Settings')}<main class="cn-app__main">${PAGE_HEADER('Change plan', 'Switch plans any time. Changes are prorated on your next invoice.', BTN('ghost', 'Back to billing', 'md'))}<div class="cn-segmented-control" data-size="md" data-variant="default" role="radiogroup" aria-label="Billing period" style="align-self:flex-start"><button type="button" class="cn-segmented-control__item" role="radio" aria-checked="true">Monthly</button><button type="button" class="cn-segmented-control__item" role="radio" aria-checked="false">Annual · save 20%</button></div><div class="cn-grid" data-cols="3" data-gap="6">${[['Basic', '$10', 'For small teams getting started.', ['Up to 10 users', 'Basic reporting', 'Email support'], false, false], ['Business', '$20', 'Your current plan.', ['Up to 20 users', 'Advanced reporting', 'Priority support', '200+ integrations'], true, false], ['Enterprise', '$40', 'Security, control and scale.', ['Unlimited users', 'Audit log', 'SSO / SAML', 'Dedicated manager'], false, true]].map(([n, p, d, items, cur, best]) => `<section class="cn-card cn-billing__plan" data-variant="default" data-padding="lg"${best ? ' data-selected' : ''}><div class="cn-card__body cn-stack" data-gap="5"><div class="cn-row" data-justify="between"><span class="cn-text-heading-sm">${n}</span>${cur ? BADGE('Current', 'accent') : best ? BADGE('Recommended', 'success') : ''}</div><span class="cn-text-heading-lg">${p}<span class="cn-text-body-sm cn-app__muted"> per user / month</span></span><span class="cn-text-body-sm cn-app__muted">${d}</span><ul class="cn-stack" data-gap="2">${(items as string[]).map((it) => `<li class="cn-row" data-gap="2"><span class="cn-billing__tick">${ICON.check}</span><span class="cn-text-body-sm">${it}</span></li>`).join('')}</ul>${cur ? BTN('outline', 'Current plan', 'md') : BTN(best ? 'primary' : 'outline', 'Switch to ' + n, 'md')}</div></section>`).join('')}</div></main></div>` },
    { title: 'Checkout', html: `<div class="cn-app">${SIDEBAR('Settings', 'slim')}<main class="cn-app__main">${PAGE_HEADER('Checkout', 'Upgrade to Enterprise · billed monthly', '')}<div class="cn-grid cn-billing__checkout" data-cols="3" data-gap="8"><form class="cn-app__span2 cn-stack" data-gap="8"><section class="cn-stack" data-gap="5"><h2 class="cn-text-heading-sm">Contact</h2>${FIELD('b-email', 'Email', INPUT('b-email', 'billing@lumen.co', 'email'))}</section><section class="cn-stack" data-gap="5"><h2 class="cn-text-heading-sm">Payment</h2>${FIELD('b-card', 'Card number', `<div class="cn-input" data-variant="default" data-size="md"><span class="cn-billing__brand cn-billing__brand--sm" aria-hidden="true">VISA</span><input class="cn-input__field" id="b-card" type="text" inputmode="numeric" placeholder="1234 1234 1234 1234"></div>`)}<div class="cn-grid" data-cols="2" data-gap="5" data-keep>${FIELD('b-exp', 'Expiry', INPUT('b-exp', '', 'text', 'MM / YY'))}${FIELD('b-cvc', 'CVC', INPUT('b-cvc', '', 'text', '123'))}</div>${FIELD('b-name', 'Name on card', INPUT('b-name', 'Maya Chen'))}${FIELD('b-country', 'Country', `<div class="cn-select" data-variant="default" data-size="md"><select class="cn-select__field" id="b-country" aria-label="Country"><option>Brazil</option><option selected>United States</option><option>Portugal</option></select><svg class="cn-select__chevron" viewBox="0 0 16 16" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="M4 6l4 4 4-4"/></svg></div>`)}</section></form><aside>${CARD(CARD_HEAD('Order summary'), `<div class="cn-stack" data-gap="4"><dl class="cn-billing__lines"><div><dt>Enterprise plan × 14 seats</dt><dd>$560.00</dd></div><div><dt>Credit from current plan</dt><dd>−$186.67</dd></div><div><dt>Tax (0%)</dt><dd>$0.00</dd></div><div class="cn-billing__total"><dt>Due today</dt><dd>$373.33</dd></div></dl><span class="cn-text-body-sm cn-app__muted">Then $560.00 on the 12th of each month. Cancel any time.</span>${BTN('primary', 'Pay $373.33', 'lg')}<span class="cn-text-body-xs cn-app__muted cn-center">Payments are processed securely. By paying you agree to the <a href="#" class="cn-link" data-variant="inline">terms</a>.</span></div>`)}</aside></div></main></div>` },
  ],
  css: `${APP_CSS}
.cn-app__span2 { grid-column: span 2; min-width: 0; }
.cn-billing__card { display: flex; align-items: center; gap: {space.4}; padding: {space.4}; border: {border.width.thin} solid {color.border-default}; border-radius: {radius.card}; }
.cn-billing__brand { display: inline-flex; align-items: center; justify-content: center; width: 46px; height: 32px; border-radius: {radius.sm}; border: {border.width.thin} solid {color.border-default}; background-color: {color.bg-surface}; font-family: {font.family.sans}; font-size: 10px; font-weight: {font.weight.bold}; letter-spacing: 0.04em; color: {brand.700}; flex-shrink: 0; }
.cn-billing__brand--sm { width: 34px; height: 22px; margin-inline-start: {space.3}; font-size: 8px; }
.cn-billing__plan[data-selected] { border-color: {color.border-action}; box-shadow: 0 0 0 1px {color.border-action}; }
.cn-billing__plan .cn-button { width: 100%; }
.cn-billing__tick { display: inline-flex; color: {color.fg-success}; }
.cn-billing__tick .cn-icon { width: 16px; height: 16px; }
.cn-billing__lines { margin: 0; display: flex; flex-direction: column; gap: {space.3}; }
.cn-billing__lines > div { display: flex; justify-content: space-between; gap: {space.4}; font-size: {font.size.sm}; color: {color.fg-muted}; }
.cn-billing__lines dd { margin: 0; color: {color.fg-default}; font-variant-numeric: tabular-nums; }
.cn-billing__total { padding-top: {space.3}; border-top: {border.width.thin} solid {color.border-default}; font-weight: {font.weight.semibold}; }
.cn-billing__total dt, .cn-billing__total dd { color: {color.fg-default}; font-size: {font.size.lg}; }
.cn-billing__checkout aside { position: sticky; top: {space.8}; }
.cn-billing__checkout .cn-button { width: 100%; }
@media (max-width: {breakpoint.md}) { .cn-app__span2 { grid-column: auto; } }`,
  viewport: 'desktop',
};
