import type { Pattern } from '../types.ts';
import { SIDEBAR, PAGE_HEADER, BTN, AVATAR, BADGE, ICON, APP_CSS, CARD, CARD_HEAD } from './_app.ts';

const AGENDA: [string, [string, string, string[], string][]][] = [['Thursday, 10 September', [['9:00', 'Design sync', ['MC', 'SA', 'NB'], 'accent'], ['15:00', 'Customer call — Catalog', ['MC', 'DC'], 'success']]], ['Friday, 11 September', [['10:00', 'Billing demo', ['DC', 'AK'], 'warning'], ['16:00', 'Retro', ['MC', 'DC', 'SA', 'LF'], 'accent']]]];
const DAYS = ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'];
const EVENTS: Record<number, [string, string, string][]> = { 2: [['9:00', 'Design sync', 'accent']], 3: [['10:30', 'Roadmap review', 'info'], ['15:00', 'Customer call', 'success']], 8: [['11:00', 'Sprint planning', 'accent']], 10: [['14:00', 'Billing demo', 'warning']], 14: [['9:30', 'Hiring loop', 'info'], ['13:00', 'Lunch & learn', 'success'], ['16:00', 'Retro', 'accent']], 17: [['10:00', 'All hands', 'accent']], 22: [['9:00', 'Design sync', 'accent']], 25: [['15:00', 'Launch go/no-go', 'danger']] };
const MONTH = `<div class="cn-cal"><div class="cn-cal__weekdays">${DAYS.map((d) => `<span>${d}</span>`).join('')}</div><div class="cn-cal__grid">${Array.from({ length: 35 }, (_, i) => { const day = i; const inMonth = day >= 1 && day <= 30; const n = inMonth ? day : day < 1 ? 31 + day : day - 30; return `<div class="cn-cal__cell"${inMonth ? '' : ' data-outside'}${day === 11 ? ' data-today' : ''}><span class="cn-cal__daynum">${n}</span>${inMonth ? (EVENTS[day] ?? []).map(([t, e, tone]) => `<span class="cn-cal__event" data-tone="${tone}"><span class="cn-cal__time">${t}</span>${e}</span>`).join('') : ''}</div>`; }).join('')}</div></div>`;
const HOURS = ['8:00', '9:00', '10:00', '11:00', '12:00', '13:00', '14:00', '15:00', '16:00', '17:00'];
const WEEK = `<div class="cn-cal cn-cal--week" role="region" tabindex="0" aria-label="Week calendar, scroll horizontally to see all days"><div class="cn-cal__weekhead"><span></span>${DAYS.slice(0, 5).map((d, i) => `<span class="cn-cal__dayhead"${i === 4 ? ' data-today' : ''}><span class="cn-text-label-sm">${d}</span><span class="cn-cal__daybig">${7 + i}</span></span>`).join('')}</div><div class="cn-cal__weekgrid">${HOURS.map((h, row) => `<span class="cn-cal__hour" style="grid-column:1;grid-row:${row + 1}">${h}</span>${DAYS.slice(0, 5).map((_, col) => `<span class="cn-cal__slot" style="grid-column:${col + 2};grid-row:${row + 1}"></span>`).join('')}`).join('')}<span class="cn-cal__block" data-tone="accent" style="grid-column:2;grid-row:2 / span 2"><span class="cn-cal__time">9:00 – 10:00</span>Design sync</span><span class="cn-cal__block" data-tone="info" style="grid-column:3;grid-row:3 / span 3"><span class="cn-cal__time">10:00 – 11:30</span>Roadmap review</span><span class="cn-cal__block" data-tone="success" style="grid-column:5;grid-row:7 / span 2"><span class="cn-cal__time">14:00 – 15:00</span>Customer call</span><span class="cn-cal__block" data-tone="warning" style="grid-column:6;grid-row:4 / span 2"><span class="cn-cal__time">11:00 – 12:00</span>Billing demo</span></div></div>`;

export const calendarPage: Pattern = {
  name: 'Calendar and scheduling',
  slug: 'calendar-page',
  category: 'app-page',
  description: 'Month grid with event chips, week view with time blocks, and an agenda list with an event detail card.',
  rules: [
    'Header: month/year title with prev/next icon buttons and a "Today" outline button; view switch (Month / Week / Day) as a segmented control; "New event" is the primary action.',
    'Month grid: 7 columns, cells ≥ 120px tall, day number top-left (label-sm), events as small chips (body-xs, 4px radius, tinted by category); outside-month days muted; today has a brand-filled day number.',
    'Week view: time column + 5–7 day columns, 1-hour rows (64px), events as blocks with a tinted background and left border; overlapping events share the column.',
    'Agenda: list grouped by day; each item time (code-sm) + title + attendees avatars; clicking opens the detail card (title, time, location, attendees, actions).',
  ],
  html: `<div class="cn-app">${SIDEBAR('Dashboard')}<main class="cn-app__main">${PAGE_HEADER('September 2026', '', `<div class="cn-segmented-control" data-size="md" data-variant="default" role="radiogroup" aria-label="View"><button type="button" class="cn-segmented-control__item" role="radio" aria-checked="true">Month</button><button type="button" class="cn-segmented-control__item" role="radio" aria-checked="false">Week</button><button type="button" class="cn-segmented-control__item" role="radio" aria-checked="false">Day</button></div>${BTN('outline', 'Today', 'md')}<div class="cn-button-group" data-variant="attached" data-orientation="horizontal"><button type="button" class="cn-button" data-variant="outline" data-size="md" data-icon="only" aria-label="Previous month">${ICON.chevronRight.replace('cn-icon', 'cn-button__icon').replace('<svg', '<svg style="transform:rotate(180deg)"')}</button><button type="button" class="cn-button" data-variant="outline" data-size="md" data-icon="only" aria-label="Next month">${ICON.chevronRight.replace('cn-icon', 'cn-button__icon')}</button></div>${BTN('primary', 'New event', 'md', ICON.plus)}`).replace('<p class="cn-page-header__description"></p>', '')}${MONTH}</main></div>`,
  variants: [
    { title: 'Week view', html: `<div class="cn-app">${SIDEBAR('Dashboard', 'slim')}<main class="cn-app__main">${PAGE_HEADER('7 – 11 September 2026', '', `<div class="cn-segmented-control" data-size="md" data-variant="default" role="radiogroup" aria-label="View"><button type="button" class="cn-segmented-control__item" role="radio" aria-checked="false">Month</button><button type="button" class="cn-segmented-control__item" role="radio" aria-checked="true">Week</button><button type="button" class="cn-segmented-control__item" role="radio" aria-checked="false">Day</button></div>${BTN('outline', 'Today', 'md')}${BTN('primary', 'New event', 'md', ICON.plus)}`).replace('<p class="cn-page-header__description"></p>', '')}${WEEK}</main></div>` },
    { title: 'Agenda with event detail', html: `<div class="cn-app">${SIDEBAR('Dashboard')}<main class="cn-app__main">${PAGE_HEADER('Agenda', 'Your next 7 days.', BTN('primary', 'New event', 'md', ICON.plus))}<div class="cn-grid" data-cols="3" data-gap="6"><div class="cn-app__span2 cn-stack" data-gap="6">${AGENDA.map(([day, items]) => `<section class="cn-stack" data-gap="2"><h2 class="cn-text-label-sm cn-app__muted">${day}</h2><div class="cn-card" data-variant="default" data-padding="none"><ul class="cn-list" data-density="default" data-variant="plain">${items.map(([t, title, ppl, tone], i) => `<li class="cn-list__item"${i === 0 && day.startsWith('Thu') ? ' data-selected' : ''}><span class="cn-list__leading"><span class="cn-cal__agenda-time" data-tone="${tone}">${t}</span></span><span class="cn-list__content"><span class="cn-list__title">${title}</span><span class="cn-list__description">45 min · Google Meet</span></span><span class="cn-list__trailing"><span class="cn-avatar-group" data-size="sm">${ppl.map((p) => AVATAR(p, p, 'sm', tone).replace('class="cn-avatar"', 'class="cn-avatar cn-avatar-group__item"')).join('')}</span></span></li>`).join('')}</ul></div></section>`).join('')}</div>${CARD(CARD_HEAD('Design sync', 'Thursday, 10 September · 9:00 – 10:00', '', BADGE('Recurring', 'accent')), `<div class="cn-stack" data-gap="5"><dl class="cn-app__dl"><div><dt>Where</dt><dd>Google Meet · Room “Aurora”</dd></div><div><dt>Attendees</dt><dd><div class="cn-stack" data-gap="2">${[['MC', 'Maya Chen', 'Organizer', 'accent'], ['SA', 'Sofia Almeida', 'Accepted', 'warning'], ['NB', 'Noah Berg', 'Tentative', 'success']].map(([i, n, s, tone]) => `<div class="cn-row" data-gap="2">${AVATAR(i, n, 'xs', tone)}<span class="cn-text-body-sm">${n}</span><span class="cn-text-body-xs cn-app__muted">${s}</span></div>`).join('')}</div></dd></div><div><dt>Notes</dt><dd>Review the settings page redesign and decide on the drawer vs. dialog for member edits.</dd></div></dl><div class="cn-row" data-gap="2">${BTN('outline', 'Edit', 'sm')}${BTN('primary', 'Join call', 'sm')}</div></div>`)}</div></main></div>` },
  ],
  css: `${APP_CSS}
.cn-app__span2 { grid-column: span 2; min-width: 0; }
.cn-cal { border: {border.width.thin} solid {color.border-default}; border-radius: {radius.card}; background-color: {color.bg-surface}; overflow: hidden; }
.cn-cal__weekdays { display: grid; grid-template-columns: repeat(7, minmax(0, 1fr)); border-bottom: {border.width.thin} solid {color.border-default}; }
.cn-cal__weekdays span { padding: {space.2} {space.3}; font-size: {font.size.xs}; font-weight: {font.weight.medium}; color: {color.fg-muted}; }
.cn-cal__grid { display: grid; grid-template-columns: repeat(7, minmax(0, 1fr)); }
.cn-cal__cell { min-width: 0; min-height: 120px; padding: {space.2}; border-inline-end: {border.width.thin} solid {color.border-subtle}; border-bottom: {border.width.thin} solid {color.border-subtle}; display: flex; flex-direction: column; gap: {space.1}; }
.cn-cal__cell:nth-child(7n) { border-inline-end: 0; }
.cn-cal__cell[data-outside] { background-color: {color.bg-subtle}; }
.cn-cal__cell[data-outside] .cn-cal__daynum { color: {color.fg-subtle}; }
.cn-cal__daynum { display: inline-flex; align-items: center; justify-content: center; width: 24px; height: 24px; border-radius: {radius.full}; font-size: {font.size.sm}; font-weight: {font.weight.medium}; color: {color.fg-muted}; }
.cn-cal__cell[data-today] .cn-cal__daynum { background-color: {color.bg-action}; color: {color.fg-on-action}; }
.cn-cal__event { display: flex; gap: {space.1}; align-items: baseline; padding: {space.0.5} {space.1.5}; border-radius: {radius.sm}; font-size: {font.size.xs}; font-weight: {font.weight.medium}; line-height: 1.4; overflow: hidden; white-space: nowrap; text-overflow: ellipsis; background-color: {color.bg-subtle}; color: {color.fg-default}; border-inline-start: 2px solid {color.border-strong}; }
.cn-cal__time { color: {color.fg-subtle}; font-weight: {font.weight.regular}; }
.cn-cal__event[data-tone="accent"], .cn-cal__block[data-tone="accent"], .cn-cal__agenda-time[data-tone="accent"] { background-color: {color.bg-action-subtle}; color: {color.fg-action}; border-color: {color.bg-action}; }
.cn-cal__event[data-tone="info"], .cn-cal__block[data-tone="info"], .cn-cal__agenda-time[data-tone="info"] { background-color: {color.bg-info-subtle}; color: {color.fg-info}; border-color: {color.bg-info}; }
.cn-cal__event[data-tone="success"], .cn-cal__block[data-tone="success"], .cn-cal__agenda-time[data-tone="success"] { background-color: {color.bg-success-subtle}; color: {color.fg-success}; border-color: {color.bg-success}; }
.cn-cal__event[data-tone="warning"], .cn-cal__block[data-tone="warning"], .cn-cal__agenda-time[data-tone="warning"] { background-color: {color.bg-warning-subtle}; color: {color.fg-warning}; border-color: {color.bg-warning}; }
.cn-cal__event[data-tone="danger"], .cn-cal__block[data-tone="danger"], .cn-cal__agenda-time[data-tone="danger"] { background-color: {color.bg-danger-subtle}; color: {color.fg-danger}; border-color: {color.bg-danger}; }
.cn-cal--week { overflow-x: auto; }
.cn-cal__weekhead { display: grid; min-width: {size.container.sm}; grid-template-columns: 64px repeat(5, minmax(0, 1fr)); border-bottom: {border.width.thin} solid {color.border-default}; }
.cn-cal__dayhead { display: flex; flex-direction: column; align-items: center; gap: {space.1}; padding: {space.3}; color: {color.fg-muted}; border-inline-start: {border.width.thin} solid {color.border-subtle}; }
.cn-cal__daybig { display: inline-flex; align-items: center; justify-content: center; width: 32px; height: 32px; border-radius: {radius.full}; font-size: {font.size.lg}; font-weight: {font.weight.semibold}; color: {color.fg-default}; }
.cn-cal__dayhead[data-today] .cn-cal__daybig { background-color: {color.bg-action}; color: {color.fg-on-action}; }
.cn-cal__weekgrid { display: grid; min-width: {size.container.sm}; grid-template-columns: 64px repeat(5, minmax(0, 1fr)); grid-auto-rows: 64px; position: relative; }
.cn-cal__hour { padding: {space.2}; font-size: {font.size.xs}; color: {color.fg-subtle}; text-align: right; border-bottom: {border.width.thin} solid {color.border-subtle}; }
.cn-cal__slot { border-inline-start: {border.width.thin} solid {color.border-subtle}; border-bottom: {border.width.thin} solid {color.border-subtle}; }
.cn-cal__block { margin: 2px 4px; padding: {space.1.5} {space.2}; border-radius: {radius.md}; border-inline-start: 3px solid; font-size: {font.size.xs}; font-weight: {font.weight.medium}; display: flex; flex-direction: column; gap: 2px; overflow: hidden; }
.cn-cal__agenda-time { display: inline-flex; align-items: center; height: 28px; padding-inline: {space.2}; border-radius: {radius.md}; font-family: {font.family.mono}; font-size: {font.size.xs}; border-inline-start: 3px solid; }
@media (max-width: {breakpoint.md}) { .cn-cal__cell { min-height: 64px; padding: {space.1}; } .cn-cal__weekdays span { padding-inline: {space.1}; text-align: center; } .cn-cal__event { display: block; font-size: {font.size.xs}; padding-inline: {space.1}; } .cn-cal__event .cn-cal__time { display: none; } .cn-app__span2 { grid-column: auto; } }`,
  viewport: 'desktop',
};
