import type { Pattern } from '../types.ts';
import { SIDEBAR, PAGE_HEADER, BTN, STAT, CHART, BARS, CARD, CARD_HEAD, TEAM_TABLE, PAGINATION, TABS, AVATAR, BADGE, ICON, APP_CSS } from './_app.ts';

const PROJECTS: [string, string, number, string, string][] = [['Website redesign', 'Marketing', 68, 'On track', 'success'], ['Mobile app 2.0', 'Product', 32, 'At risk', 'warning'], ['Billing platform', 'Engineering', 91, 'On track', 'success'], ['Brand refresh', 'Design', 12, 'Planning', 'neutral'], ['Data warehouse', 'Engineering', 47, 'Blocked', 'danger'], ['Onboarding flow', 'Product', 80, 'On track', 'success']];
const METRICS = `<div class="cn-grid" data-cols="4" data-gap="6" data-keep>${STAT('Total customers', '2,420', '+40%')}${STAT('Members', '1,210', '+10%')}${STAT('Active now', '316', '−2%', 'down')}${STAT('Conversion', '4.2%', '+0.4%')}</div>`;
const CHART_CARD = CARD(CARD_HEAD('Revenue', 'Monthly recurring revenue, last 12 months', `${TABS(['12 months', '30 days', '7 days'], 0, 'pill')}`), `<div class="cn-stack" data-gap="4"><div class="cn-row" data-justify="between"><span class="cn-text-heading-lg">$128,430</span><span class="cn-app__legend"><span>This year</span><span>Last year</span></span></div>${CHART(260)}</div>`);
const ACTIVITY = CARD(CARD_HEAD('Recent activity', '', BTN('link-color', 'View all', 'sm')), `<ul class="cn-list" data-density="default" data-variant="plain">${[['MC', 'Maya Chen', 'commented on Q3 roadmap', '2m', 'accent'], ['DC', 'Daniel Costa', 'merged “Billing refactor”', '14m', 'success'], ['SA', 'Sofia Almeida', 'uploaded 3 files to Brand', '1h', 'warning'], ['LF', 'Lucas Ferreira', 'invited Elena Rossi', '3h', 'info']].map(([i, n, a, t, tone]) => `<li class="cn-list__item"><span class="cn-list__leading">${AVATAR(i, n, 'sm', tone)}</span><span class="cn-list__content"><span class="cn-list__title">${n}</span><span class="cn-list__description">${a}</span></span><span class="cn-list__trailing">${t}</span></li>`).join('')}</ul>`);
const TABLE_CARD = `<section class="cn-card cn-app__table-card" data-variant="default" data-padding="none"><div class="cn-section-header" data-variant="card" data-divider="yes">${CARD_HEAD('Team members', 'Manage your team members and their account permissions here.', `${BTN('outline', 'Download all', 'md', ICON.copy)}${BTN('primary', 'Add member', 'md', ICON.plus)}`, BADGE('100 users', 'accent'))}</div><div class="cn-card__body cn-app__card-body cn-app__card-body--flush" role="region" tabindex="0" aria-label="Scrollable table">${TEAM_TABLE()}</div><footer class="cn-card__footer">${PAGINATION}</footer></section>`;

export const dashboardPage: Pattern = {
  name: 'Dashboard',
  slug: 'dashboard-page',
  category: 'app-page',
  description: 'Application home: sidebar, page header with the primary action, a metrics row, a chart card with an activity list, and a data table card. Three layouts.',
  rules: [
    'Structure: .cn-app (flex) → Sidebar + .cn-app__main (32px padding, 32px gap between blocks). Use the Sidebar component’s current width and navigation density.',
    'Order: page header → metrics (4 stat cards, 24px gap) → chart + activity (2:1 grid) → table card with its own header and pagination footer.',
    'Exactly one primary button on the page (in the header); card headers use outline/link buttons.',
    'Charts live inside a card with a section header (title, description, period tabs) and a legend; no 3D, no gradients, brand color for the main series and brand-300 for the secondary.',
    'Below 1024px the sidebar hides (use the MobileHeader) and grids collapse: metrics 2×2, chart and activity stacked.',
  ],
  html: `<div class="cn-app">${SIDEBAR('Dashboard')}<main class="cn-app__main">${PAGE_HEADER('Welcome back, Maya', 'Track, manage and forecast your customers and orders.', `${BTN('outline', 'Export', 'md', ICON.external)}${BTN('primary', 'New report', 'md', ICON.plus)}`)}${METRICS}<div class="cn-grid" data-cols="3" data-gap="6"><div class="cn-app__span2">${CHART_CARD}</div>${ACTIVITY}</div>${TABLE_CARD}</main></div>`,
  variants: [
    { title: 'Analytics with tabs and bar chart', html: `<div class="cn-app">${SIDEBAR('Reporting', 'slim')}<main class="cn-app__main">${PAGE_HEADER('Reporting', 'Performance across every channel.', `${BTN('outline', 'Share', 'md')}${BTN('primary', 'Create report', 'md')}`, 'with-tabs', '')}<div class="cn-page-header__tabs" >${TABS(['Overview', 'Traffic', 'Sales', 'Retention', 'Cohorts'], 0)}</div>${METRICS}${CARD(CARD_HEAD('Sessions by channel', 'Unique sessions, last 12 months', BTN('outline', 'Filters', 'sm')), `<div class="cn-stack" data-gap="4"><span class="cn-app__legend"><span>Organic</span><span>Paid</span></span>${BARS(280)}</div>`)}<div class="cn-grid" data-cols="2" data-gap="6">${CARD(CARD_HEAD('Top pages', '', BTN('link-color', 'View all', 'sm')), `<ul class="cn-list" data-density="compact" data-variant="plain">${[['/pricing', '12,430', '+8%'], ['/blog/design-systems', '9,214', '+24%'], ['/', '8,102', '−3%'], ['/docs', '6,320', '+2%']].map(([p, v, d]) => `<li class="cn-list__item"><span class="cn-list__content"><span class="cn-list__title">${p}</span></span><span class="cn-list__trailing"><span class="cn-text-label-sm">${v}</span>${BADGE(d, d.startsWith('−') ? 'danger' : 'success')}</span></li>`).join('')}</ul>`)}${CARD(CARD_HEAD('Conversion funnel', '', BTN('link-color', 'View report', 'sm')), `<div class="cn-stack" data-gap="4">${[['Visited', 100, '24,020'], ['Signed up', 42, '10,088'], ['Activated', 28, '6,725'], ['Paid', 9, '2,161']].map(([l, w, n]) => `<div class="cn-progress" data-size="md" data-tone="action" role="progressbar" aria-valuenow="${w}" aria-valuemin="0" aria-valuemax="100" aria-label="${l}"><div class="cn-progress__header"><span class="cn-progress__label">${l}</span><span class="cn-progress__value">${n}</span></div><div class="cn-progress__track"><div class="cn-progress__indicator" style="width:${w}%"></div></div></div>`).join('')}</div>`)}</div></main></div>` },
    { title: 'Dark sidebar, project overview', html: `<div class="cn-app">${SIDEBAR('Projects', 'simple', 'dark')}<main class="cn-app__main">${PAGE_HEADER('Projects', 'Every project your team is working on this quarter.', `${BTN('outline', 'Import', 'md')}${BTN('primary', 'New project', 'md', ICON.plus)}`)}<div class="cn-grid" data-cols="3" data-gap="6">${PROJECTS.map(([t, team, p, st, tone]) => `<section class="cn-card" data-variant="default" data-padding="md"><div class="cn-card__body cn-stack" data-gap="4"><div class="cn-row" data-justify="between"><span class="cn-text-heading-xs">${t}</span>${BADGE(st, tone, 'soft', true)}</div><span class="cn-text-body-sm cn-app__muted">${team} · 4 members</span><div class="cn-progress" data-size="sm" data-tone="action" role="progressbar" aria-valuenow="${p}" aria-valuemin="0" aria-valuemax="100" aria-label="Progress"><div class="cn-progress__header"><span class="cn-progress__label">Progress</span><span class="cn-progress__value">${p}%</span></div><div class="cn-progress__track"><div class="cn-progress__indicator" style="width:${p}%"></div></div></div><div class="cn-row" data-justify="between"><div class="cn-avatar-group" data-size="sm">${AVATAR('MC', 'Maya Chen', 'sm', 'accent').replace('class="cn-avatar"', 'class="cn-avatar cn-avatar-group__item"')}${AVATAR('DC', 'Daniel Costa', 'sm', 'success').replace('class="cn-avatar"', 'class="cn-avatar cn-avatar-group__item"')}${AVATAR('SA', 'Sofia Almeida', 'sm', 'warning').replace('class="cn-avatar"', 'class="cn-avatar cn-avatar-group__item"')}</div>${BTN('link-color', 'Open', 'sm')}</div></div></section>`).join('')}</div></main></div>` },
  ],
  css: `${APP_CSS}
.cn-app__span2 { grid-column: span 2; min-width: 0; }
@media (max-width: {breakpoint.md}) { .cn-app__span2 { grid-column: auto; } }`,
  viewport: 'desktop',
};
