import type { Pattern } from '../types.ts';
import { SIDEBAR, PAGE_HEADER, BTN, TABS, AVATAR, BADGE, ICON, APP_CSS, CHECKBOX, PAGINATION, IMG } from './_app.ts';

const FILES = [['Brand guidelines v3.pdf', 'PDF', '4.2 MB', 'Sofia Almeida', 'SA', 'warning', 'Today'], ['Q3 roadmap.fig', 'Figma', '18.6 MB', 'Maya Chen', 'MC', 'accent', 'Yesterday'], ['Billing migration plan.docx', 'Document', '212 KB', 'Daniel Costa', 'DC', 'success', 'Mon'], ['Onboarding screens.png', 'Image', '1.8 MB', 'Noah Berg', 'NB', 'success', 'Mon'], ['Customer interviews.csv', 'Spreadsheet', '96 KB', 'Aisha Khan', 'AK', 'accent', 'Last week'], ['Launch checklist.md', 'Markdown', '12 KB', 'Lucas Ferreira', 'LF', 'info', 'Last week']];
const fileIcon = `<span class="cn-files__icon" aria-hidden="true">${ICON.copy}</span>`;
const CRUMBS = `<nav class="cn-breadcrumb" data-size="md" aria-label="Breadcrumb"><ol class="cn-breadcrumb__list"><li class="cn-breadcrumb__item"><a class="cn-breadcrumb__link" href="#">Files</a></li><li class="cn-breadcrumb__separator" aria-hidden="true">${ICON.chevronRight}</li><li class="cn-breadcrumb__item"><a class="cn-breadcrumb__link" href="#">Product</a></li><li class="cn-breadcrumb__separator" aria-hidden="true">${ICON.chevronRight}</li><li class="cn-breadcrumb__item"><span class="cn-breadcrumb__current" aria-current="page">Q3 launch</span></li></ol></nav>`;
const TOOLBAR = `<div class="cn-row" data-justify="between" data-gap="3" data-wrap><div class="cn-row" data-gap="3"><div class="cn-input" data-variant="default" data-size="md" style="width:320px">${ICON.search.replace('cn-icon', 'cn-input__icon')}<input class="cn-input__field" type="search" placeholder="Search files" aria-label="Search files"></div>${BTN('outline', 'Type', 'md', ICON.chevronDown)}${BTN('outline', 'Owner', 'md', ICON.chevronDown)}</div><div class="cn-segmented-control" data-size="md" data-variant="default" role="radiogroup" aria-label="View"><button type="button" class="cn-segmented-control__item" role="radio" aria-checked="true">List</button><button type="button" class="cn-segmented-control__item" role="radio" aria-checked="false">Grid</button></div></div>`;
const TABLE = `<table class="cn-table" data-density="default" data-variant="default" data-interactive><thead class="cn-table__head"><tr class="cn-table__row"><th class="cn-table__header-cell" scope="col" style="width:48px">${CHECKBOX()}</th><th class="cn-table__header-cell" scope="col">Name</th><th class="cn-table__header-cell" scope="col">Type</th><th class="cn-table__header-cell" scope="col" data-align="right">Size</th><th class="cn-table__header-cell" scope="col">Owner</th><th class="cn-table__header-cell" scope="col">Modified</th><th class="cn-table__header-cell" scope="col"><span class="cn-sr-only">Actions</span></th></tr></thead><tbody class="cn-table__body">${FILES.map(([n, t, s, o, i, tone, d], k) => `<tr class="cn-table__row"${k === 1 ? ' data-selected' : ''}><td class="cn-table__cell">${CHECKBOX('', k === 1)}</td><td class="cn-table__cell"><div class="cn-row" data-gap="3">${fileIcon}<span class="cn-text-label-sm">${n}</span></div></td><td class="cn-table__cell">${BADGE(t)}</td><td class="cn-table__cell" data-align="right">${s}</td><td class="cn-table__cell"><div class="cn-row" data-gap="2">${AVATAR(i, o, 'xs', tone)}<span>${o}</span></div></td><td class="cn-table__cell">${d}</td><td class="cn-table__cell cn-table__actions"><div class="cn-row" data-gap="1" data-justify="end"><button type="button" class="cn-icon-button" data-variant="ghost" data-size="sm" data-shape="square" aria-label="Download">${ICON.external.replace('cn-icon', 'cn-icon-button__icon')}</button><button type="button" class="cn-icon-button" data-variant="ghost" data-size="sm" data-shape="square" aria-label="More">${ICON.dots.replace('cn-icon', 'cn-icon-button__icon')}</button></div></td></tr>`).join('')}</tbody></table>`;

export const filesPage: Pattern = {
  name: 'Files and documents',
  slug: 'files-page',
  category: 'app-page',
  description: 'A file manager: breadcrumbs, toolbar (search, filters, list/grid toggle), a selectable table of files with owner and size, or a grid of file cards with previews; an upload dropzone and a details drawer.',
  rules: [
    'Breadcrumbs above the page title show the folder path (max 3 levels shown, the rest collapsed).',
    'Toolbar: search (320) + filter buttons on the left, list/grid segmented control on the right.',
    'List: table with checkbox, icon + name (label-sm), type badge, size right-aligned, owner (avatar xs + name), modified, and ghost icon actions. Selected rows get the action-subtle fill.',
    'Grid: cards with a 16:10 preview, name, type badge and size; 4 per row, 24px gap.',
    'Upload: a dropzone card at the top when the folder is empty or on hover of the page in real apps; never a floating "+" button.',
  ],
  html: `<div class="cn-app">${SIDEBAR('Projects')}<main class="cn-app__main">${PAGE_HEADER('Q3 launch', '6 files · 25.1 MB · shared with 8 people', `${BTN('outline', 'Share', 'md', ICON.user)}${BTN('primary', 'Upload', 'md', ICON.plus)}`, 'simple', `<div class="cn-page-header__crumbs">${CRUMBS}</div>`)}${TOOLBAR}<section class="cn-card cn-app__table-card" data-variant="default" data-padding="none"><div class="cn-card__body cn-app__card-body cn-app__card-body--flush" role="region" tabindex="0" aria-label="Scrollable table">${TABLE}</div><footer class="cn-card__footer">${PAGINATION}</footer></section></main></div>`,
  variants: [
    { title: 'Grid with upload dropzone', html: `<div class="cn-app">${SIDEBAR('Projects')}<main class="cn-app__main">${PAGE_HEADER('Q3 launch', '6 files · 25.1 MB · shared with 8 people', `${BTN('outline', 'Share', 'md', ICON.user)}${BTN('primary', 'Upload', 'md', ICON.plus)}`, 'simple', `<div class="cn-page-header__crumbs">${CRUMBS}</div>`)}<div class="cn-file-dropzone" data-size="md"><input class="cn-file-dropzone__input" type="file" multiple aria-label="Upload files"><span class="cn-file-dropzone__icon" aria-hidden="true">${ICON.copy}</span><span class="cn-file-dropzone__title"><strong>Click to upload</strong> or drag and drop</span><span class="cn-file-dropzone__hint">Any file up to 50 MB</span></div>${TOOLBAR.replace('aria-checked="true">List', 'aria-checked="false">List').replace('aria-checked="false">Grid', 'aria-checked="true">Grid')}<div class="cn-grid" data-cols="4" data-gap="6">${FILES.map(([n, t, s]) => `<article class="cn-card" data-variant="default" data-padding="none"><div class="cn-files__preview">${IMG('16 / 10', 'data-radius="none"')}</div><div class="cn-card__body cn-app__card-body cn-stack" data-gap="2" style="padding:var(--cn-space-4)"><div class="cn-row" data-justify="between" data-gap="2"><span class="cn-text-label-sm cn-truncate">${n}</span><button type="button" class="cn-icon-button" data-variant="ghost" data-size="xs" data-shape="square" aria-label="More">${ICON.dots.replace('cn-icon', 'cn-icon-button__icon')}</button></div><div class="cn-row" data-gap="2">${BADGE(t)}<span class="cn-text-body-sm cn-app__muted">${s}</span></div></div></article>`).join('')}</div></main></div>` },
    { title: 'With details drawer', html: `<div class="cn-app">${SIDEBAR('Projects', 'slim')}<main class="cn-app__main">${PAGE_HEADER('Q3 launch', '6 files', BTN('primary', 'Upload', 'md', ICON.plus), 'simple', `<div class="cn-page-header__crumbs">${CRUMBS}</div>`)}<section class="cn-card cn-app__table-card" data-variant="default" data-padding="none"><div class="cn-card__body cn-app__card-body cn-app__card-body--flush" role="region" tabindex="0" aria-label="Scrollable table">${TABLE}</div></section></main><aside class="cn-app__drawer" aria-label="File details"><div class="cn-app__drawer-head"><div class="cn-row" data-gap="3">${fileIcon}<div class="cn-stack" data-gap="0"><span class="cn-text-heading-xs">Q3 roadmap.fig</span><span class="cn-text-body-sm cn-app__muted">Figma · 18.6 MB</span></div></div><button type="button" class="cn-close-button" data-size="sm" data-theme="light" aria-label="Close">${ICON.x.replace('cn-icon', 'cn-close-button__icon')}</button></div><div class="cn-app__drawer-body">${IMG('16 / 10')}${TABS(['Details', 'Activity', 'Versions'], 0)}<dl class="cn-app__dl"><div><dt>Owner</dt><dd><div class="cn-row" data-gap="2">${AVATAR('MC', 'Maya Chen', 'xs', 'accent')}<span>Maya Chen</span></div></dd></div><div><dt>Created</dt><dd>2 September 2026</dd></div><div><dt>Modified</dt><dd>Yesterday, 18:40</dd></div><div><dt>Shared with</dt><dd><div class="cn-avatar-group" data-size="sm">${AVATAR('DC', 'Daniel Costa', 'sm', 'success').replace('class="cn-avatar"', 'class="cn-avatar cn-avatar-group__item"')}${AVATAR('SA', 'Sofia Almeida', 'sm', 'warning').replace('class="cn-avatar"', 'class="cn-avatar cn-avatar-group__item"')}${AVATAR('LF', 'Lucas Ferreira', 'sm', 'info').replace('class="cn-avatar"', 'class="cn-avatar cn-avatar-group__item"')}<span class="cn-avatar-group__overflow">+5</span></div></dd></div><div><dt>Tags</dt><dd><div class="cn-row" data-gap="1">${BADGE('Design', 'accent')}${BADGE('Q3')}</div></dd></div></dl></div><div class="cn-app__drawer-foot">${BTN('outline', 'Move', 'md')}${BTN('primary', 'Download', 'md')}</div></aside></div>` },
  ],
  css: `${APP_CSS}
.cn-files__icon { display: inline-flex; align-items: center; justify-content: center; width: 40px; height: 40px; border-radius: {radius.lg}; background-color: {color.bg-subtle}; color: {color.fg-muted}; flex-shrink: 0; }
.cn-files__icon .cn-icon { width: 20px; height: 20px; }
.cn-files__preview { border-bottom: {border.width.thin} solid {color.border-default}; }
.cn-files__preview .cn-placeholder { border-radius: 0; }`,
  viewport: 'desktop',
};
