import type { Pattern } from '../types.ts';
import { SIDEBAR, PAGE_HEADER, BTN, ICON, APP_CSS, CARD, CARD_HEAD, AVATAR } from './_app.ts';

const STEP = (done: boolean, title: string, desc: string, action: string) => `<li class="cn-first-run__step" data-done="${done}"><span class="cn-first-run__check" aria-hidden="true">${done ? ICON.check : ''}</span><span class="cn-stack cn-flex-1" data-gap="0"><span class="cn-text-label-sm${done ? ' cn-first-run__done' : ''}">${title}</span><span class="cn-text-body-sm cn-app__muted">${desc}</span></span>${done ? '' : BTN('outline', action, 'sm')}</li>`;
const CHECKLIST = `<section class="cn-card" data-variant="default" data-padding="none"><div class="cn-section-header" data-variant="card" data-divider="yes">${CARD_HEAD('Get started with Lumen', '2 of 5 steps done · about 8 minutes left', BTN('ghost', 'Dismiss', 'sm'))}</div><div class="cn-card__body cn-app__card-body cn-app__card-body--flush"><div class="cn-progress" data-size="sm" data-tone="action" role="progressbar" aria-valuenow="40" aria-valuemin="0" aria-valuemax="100" aria-label="Setup progress" style="padding:var(--cn-space-4) var(--cn-space-6) 0"><div class="cn-progress__track"><div class="cn-progress__indicator" style="width:40%"></div></div></div><ol class="cn-first-run__list">${STEP(true, 'Create your workspace', 'Done on 11 September', '')}${STEP(true, 'Invite your team', '2 people joined', '')}${STEP(false, 'Import your customers', 'CSV or connect your CRM in one click.', 'Import')}${STEP(false, 'Connect Slack', 'Get notified where your team already talks.', 'Connect')}${STEP(false, 'Create your first report', 'Pick a template to see your data in minutes.', 'Create')}</ol></div></section>`;
const EMPTY = (icon: string, title: string, text: string, actions: string) => `<div class="cn-empty-state" data-size="md" data-variant="default"><svg class="cn-empty-state__icon" viewBox="0 0 16 16" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" aria-hidden="true">${icon}</svg><h3 class="cn-empty-state__title">${title}</h3><p class="cn-empty-state__description">${text}</p><div class="cn-empty-state__actions">${actions}</div></div>`;

export const firstRun: Pattern = {
  name: 'First run and empty states',
  slug: 'first-run',
  category: 'app-page',
  description: 'What the app looks like before there is data: a dashboard with a setup checklist and empty widgets, an empty table with an import call to action, a no-results state and an error state.',
  rules: [
    'A setup checklist card replaces the metrics on the first visit: title, progress ("2 of 5 steps"), a progress bar and steps with a check circle, title, one-line description and an outline action; done steps are struck through and lose their button.',
    'Empty widgets keep their card and header so the layout does not jump when data arrives; the body shows a small EmptyState (icon, one line, one link button).',
    'Empty table: keep the page header, filters and the card; the body shows an EmptyState with the primary action ("Import customers") and a secondary ("Add manually").',
    'No results: keep the search term visible in the description and offer "Clear search" (outline) before any primary action.',
    'Error state: featured icon error outline, plain language ("We couldn’t load your customers"), a retry button and a support link; never a stack trace.',
  ],
  html: `<div class="cn-app">${SIDEBAR('Dashboard')}<main class="cn-app__main">${PAGE_HEADER('Welcome to Lumen, Maya', 'Let’s get your workspace ready. You can come back to this any time.', BTN('primary', 'Import customers', 'md', ICON.plus))}${CHECKLIST}<div class="cn-grid" data-cols="3" data-gap="6">${CARD(CARD_HEAD('Revenue'), EMPTY('<path d="M2.5 13.5h11M4.5 11V7M8 11V4M11.5 11V8.5"/>', 'No revenue yet', 'Connect your billing provider to see revenue here.', BTN('link-color', 'Connect billing', 'sm')))}${CARD(CARD_HEAD('Customers'), EMPTY('<circle cx="8" cy="5.5" r="2.75"/><path d="M2.75 13.5c.6-2.6 2.6-4 5.25-4s4.65 1.4 5.25 4"/>', 'No customers yet', 'Import a CSV or add your first customer.', BTN('link-color', 'Import', 'sm')))}${CARD(CARD_HEAD('Activity'), EMPTY('<rect x="2.5" y="3.5" width="11" height="10" rx="1.5"/><path d="M2.5 7h11M5.5 2v3M10.5 2v3"/>', 'Nothing happened yet', 'Activity from your team will show up here.', ''))}</div></main></div>`,
  variants: [
    { title: 'Empty table with import CTA', html: `<div class="cn-app">${SIDEBAR('Users')}<main class="cn-app__main">${PAGE_HEADER('Customers', 'Everyone who bought from you, in one place.', `${BTN('outline', 'Add manually', 'md')}${BTN('primary', 'Import customers', 'md', ICON.plus)}`)}<div class="cn-row" data-gap="3"><div class="cn-input" data-variant="default" data-size="md" style="width:320px">${ICON.search.replace('cn-icon', 'cn-input__icon')}<input class="cn-input__field" type="search" placeholder="Search" aria-label="Search customers" disabled></div>${BTN('outline', 'Filters', 'md', ICON.menu).replace('class="cn-button"', 'class="cn-button" disabled')}</div><section class="cn-card" data-variant="default" data-padding="none"><div class="cn-card__body" style="padding:var(--cn-space-16) var(--cn-space-6)"><div class="cn-empty-state" data-size="lg" data-variant="default"><span class="cn-featured-icon" data-theme="modern" data-tone="gray" data-size="lg" data-shape="square">${ICON.user.replace('cn-icon', 'cn-featured-icon__icon')}</span><h3 class="cn-empty-state__title">No customers yet</h3><p class="cn-empty-state__description">Import a CSV from your previous tool or connect your CRM. We’ll match fields automatically and you can review before anything is saved.</p><div class="cn-empty-state__actions">${BTN('outline', 'Add manually', 'md')}${BTN('primary', 'Import customers', 'md', ICON.plus)}</div></div></div></section></main></div>` },
    { title: 'No results for a search', html: `<div class="cn-app">${SIDEBAR('Users')}<main class="cn-app__main">${PAGE_HEADER('Customers', '2,420 customers', BTN('primary', 'Add customer', 'md', ICON.plus))}<div class="cn-row" data-gap="3"><div class="cn-input" data-variant="default" data-size="md" style="width:320px">${ICON.search.replace('cn-icon', 'cn-input__icon')}<input class="cn-input__field" type="search" value="acme corporation" aria-label="Search customers"></div>${BTN('outline', 'Filters', 'md', ICON.menu)}<span class="cn-text-body-sm cn-app__muted">0 results</span></div><section class="cn-card" data-variant="default" data-padding="none"><div class="cn-card__body" style="padding:var(--cn-space-12) var(--cn-space-6)"><div class="cn-empty-state" data-size="md" data-variant="default"><span class="cn-featured-icon" data-theme="modern" data-tone="gray" data-size="lg" data-shape="square">${ICON.search.replace('cn-icon', 'cn-featured-icon__icon')}</span><h3 class="cn-empty-state__title">No results for “acme corporation”</h3><p class="cn-empty-state__description">Check the spelling or try a shorter term. You can also search by email, company or tag.</p><div class="cn-empty-state__actions">${BTN('outline', 'Clear search', 'md')}${BTN('primary', 'Add customer', 'md')}</div></div></div></section></main></div>` },
    { title: 'Error state', html: `<div class="cn-app">${SIDEBAR('Users')}<main class="cn-app__main">${PAGE_HEADER('Customers', '', BTN('primary', 'Add customer', 'md', ICON.plus)).replace('<p class="cn-page-header__description"></p>', '')}<section class="cn-card" data-variant="default" data-padding="none"><div class="cn-card__body" style="padding:var(--cn-space-16) var(--cn-space-6)"><div class="cn-empty-state" data-size="md" data-variant="default"><span class="cn-featured-icon" data-theme="outline" data-tone="error" data-size="lg" data-shape="circle">${ICON.warning.replace('cn-icon', 'cn-featured-icon__icon')}</span><h3 class="cn-empty-state__title">We couldn’t load your customers</h3><p class="cn-empty-state__description">Something went wrong on our side. Your data is safe. Try again in a moment, or let us know if it keeps happening.</p><div class="cn-empty-state__actions">${BTN('outline', 'Contact support', 'md')}${BTN('primary', 'Try again', 'md')}</div></div></div></section></main></div>` },
  ],
  css: `${APP_CSS}
.cn-first-run__list { list-style: none; margin: 0; padding: {space.2} 0 0; display: flex; flex-direction: column; }
.cn-first-run__step { display: flex; align-items: center; gap: {space.4}; padding: {space.4} {space.6}; border-top: {border.width.thin} solid {color.border-subtle}; }
.cn-first-run__check { display: inline-flex; align-items: center; justify-content: center; width: 24px; height: 24px; border-radius: {radius.full}; border: {border.width.thin} solid {color.border-strong}; color: {color.fg-on-action}; flex-shrink: 0; }
.cn-first-run__step[data-done="true"] .cn-first-run__check { background-color: {color.bg-success}; border-color: {color.bg-success}; }
.cn-first-run__check .cn-icon { width: 14px; height: 14px; }
.cn-first-run__done { text-decoration: line-through; color: {color.fg-muted}; }`,
  viewport: 'desktop',
};
