import type { Pattern } from '../types.ts';
import { SIDEBAR, PAGE_HEADER, BTN, TABS, AVATAR, BADGE, ICON, APP_CSS, PEOPLE } from './_app.ts';

const THREADS = [['MC', 'Maya Chen', 'Q3 roadmap review', 'Can we move the review to Thursday? I want to include the billing numbers…', '9:41', true, 'accent'], ['DC', 'Daniel Costa', 'Billing refactor merged', 'PR #482 is in. Migrations run on deploy; nothing to do on your side.', '8:20', false, 'success'], ['SA', 'Sofia Almeida', 'Brand assets v3', 'Uploaded the new logo set and the updated icon grid to the Brand folder.', 'Yesterday', false, 'warning'], ['LF', 'Lucas Ferreira', 'Drawer focus trap', 'Found the bug: focus escapes the drawer when tabbing from the last button…', 'Yesterday', true, 'info'], ['AK', 'Aisha Khan', 'Webhook retries', 'Retries now back off exponentially; alert threshold set to 5 failures.', 'Mon', false, 'accent'], ['NB', 'Noah Berg', 'Onboarding copy', 'Draft of the three onboarding screens attached. Tone check?', 'Mon', false, 'success']];
const thread = ([i, n, s, p, t, unread, tone]: (string | boolean)[], active = false) => `<a href="#" class="cn-inbox__thread${active ? ' cn-inbox__thread--active' : ''}"${unread ? ' data-unread' : ''}>${AVATAR(i as string, n as string, 'md', tone as string, 'online')}<span class="cn-inbox__thread-body"><span class="cn-row" data-justify="between" data-gap="2"><span class="cn-text-label-sm cn-inbox__name">${n}</span><span class="cn-text-body-xs cn-app__muted">${t}</span></span><span class="cn-text-label-sm cn-inbox__subject">${s}</span><span class="cn-text-body-sm cn-app__muted cn-inbox__preview">${p}</span></span></a>`;
const MSG = (i: string, n: string, tone: string, time: string, body: string) => `<article class="cn-inbox__msg"><header class="cn-row" data-gap="3">${AVATAR(i, n, 'md', tone)}<div class="cn-stack" data-gap="0"><span class="cn-text-label-sm">${n}</span><span class="cn-text-body-xs cn-app__muted">${time}</span></div></header><div class="cn-inbox__msg-body cn-text-body-md">${body}</div></article>`;
const READING = `<section class="cn-inbox__reading"><header class="cn-inbox__reading-head"><div class="cn-stack" data-gap="1"><h2 class="cn-text-heading-sm">Q3 roadmap review</h2><div class="cn-row" data-gap="2">${BADGE('Product', 'accent')}${BADGE('Needs reply', 'warning', 'soft', true)}</div></div><div class="cn-row" data-gap="1"><button type="button" class="cn-icon-button" data-variant="ghost" data-size="md" data-shape="square" aria-label="Archive">${ICON.inbox.replace('cn-icon', 'cn-icon-button__icon')}</button><button type="button" class="cn-icon-button" data-variant="ghost" data-size="md" data-shape="square" aria-label="Delete">${ICON.trash.replace('cn-icon', 'cn-icon-button__icon')}</button><button type="button" class="cn-icon-button" data-variant="ghost" data-size="md" data-shape="square" aria-label="More">${ICON.dots.replace('cn-icon', 'cn-icon-button__icon')}</button></div></header><div class="cn-inbox__messages">${MSG('MC', 'Maya Chen', 'accent', 'Today, 9:41', '<p>Hi Daniel,</p><p>Can we move the roadmap review to Thursday? I want to include the billing numbers from the new dashboard and they only close on Wednesday night.</p><p>If Thursday doesn’t work, Friday morning is also fine for me.</p><p>Thanks,<br>Maya</p>')}${MSG('DC', 'Daniel Costa', 'success', 'Today, 10:02', '<p>Thursday works. I’ll update the invite and add Sofia so the brand assets are covered in the same session.</p>')}</div><footer class="cn-inbox__composer"><div class="cn-textarea" data-size="md" data-resize="none"><textarea class="cn-textarea__field" rows="3" placeholder="Reply to Maya…" aria-label="Reply"></textarea></div><div class="cn-row" data-justify="between"><div class="cn-row" data-gap="1"><button type="button" class="cn-icon-button" data-variant="ghost" data-size="sm" data-shape="square" aria-label="Attach file">${ICON.copy.replace('cn-icon', 'cn-icon-button__icon')}</button><button type="button" class="cn-icon-button" data-variant="ghost" data-size="sm" data-shape="square" aria-label="Insert link">${ICON.external.replace('cn-icon', 'cn-icon-button__icon')}</button></div><div class="cn-row" data-gap="2">${BTN('ghost', 'Save draft', 'sm')}${BTN('primary', 'Send', 'sm')}</div></div></footer></section>`;
const LIST = (active = 0) => `<section class="cn-inbox__list"><div class="cn-inbox__list-head"><div class="cn-row" data-justify="between"><h2 class="cn-text-heading-xs">Inbox <span class="cn-text-body-sm cn-app__muted">24</span></h2><button type="button" class="cn-icon-button" data-variant="ghost" data-size="sm" data-shape="square" aria-label="Compose">${ICON.plus.replace('cn-icon', 'cn-icon-button__icon')}</button></div><div class="cn-input" data-variant="default" data-size="sm">${ICON.search.replace('cn-icon', 'cn-input__icon')}<input class="cn-input__field" type="search" placeholder="Search messages" aria-label="Search messages"></div>${TABS(['All', 'Unread', 'Flagged'], 0, 'pill')}</div><div class="cn-inbox__threads">${THREADS.map((t, i) => thread(t, i === active)).join('')}</div></section>`;

export const inboxPage: Pattern = {
  name: 'Inbox and messaging',
  slug: 'inbox-page',
  category: 'app-page',
  description: 'Three-pane inbox (sidebar, thread list, reading pane with composer), a chat conversation layout, and a notification center. The list stays visible while reading.',
  rules: [
    'Three panes: navigation sidebar (296), thread list (360, own scroll, search + filter tabs at the top), reading pane (flex 1) with a header (subject, badges, actions), the messages and a sticky composer.',
    'Thread row: avatar 40 with presence, name label-sm + time body-xs on one line, subject label-sm, one-line preview body-sm muted; unread rows show a brand dot and semibold name; the open thread has the subtle fill.',
    'Messages are separated by 24px; each has the sender row (avatar 40, name, time) and the body in body-md with 16px paragraph spacing.',
    'Composer: textarea (3 rows, no resize) + toolbar of ghost icon buttons on the left and Save draft / Send on the right; Send is the only primary button on the page.',
    'Chat variant: bubbles max 70% wide, incoming on the left in bg-subtle, outgoing on the right in the action color; a date divider chip between days.',
    'Notification center: a list grouped by day, each item with avatar, actor + action text, time, and an unread dot; "Mark all as read" as a link button in the header.',
  ],
  html: `<div class="cn-app">${SIDEBAR('Home')}${LIST(0)}${READING}</div>`,
  variants: [
    { title: 'Chat conversation', html: `<div class="cn-app">${SIDEBAR('Home', 'slim')}${LIST(3)}<section class="cn-inbox__reading"><header class="cn-inbox__reading-head"><div class="cn-row" data-gap="3">${AVATAR('LF', 'Lucas Ferreira', 'md', 'info', 'online')}<div class="cn-stack" data-gap="0"><span class="cn-text-heading-xs">Lucas Ferreira</span><span class="cn-text-body-sm cn-app__muted">Online · Frontend</span></div></div><div class="cn-row" data-gap="2">${BTN('outline', 'Call', 'sm')}${BTN('outline', 'Profile', 'sm')}</div></header><div class="cn-inbox__chat"><div class="cn-inbox__day"><span>Today</span></div>${[['in', 'Found the bug: focus escapes the drawer when tabbing from the last button. It jumps back to the page behind.', '10:12'], ['out', 'Nice catch. Is it only the users drawer or all of them?', '10:14'], ['in', 'All of them — the trap is on the wrapper but the footer buttons render outside it.', '10:15'], ['out', 'I’ll move the footer inside the trap and add a test. Give me 20 minutes.', '10:16'], ['in', 'Perfect. I’ll re-test on Safari too.', '10:16']].map(([d, t, time]) => `<div class="cn-inbox__bubble-row" data-direction="${d}">${d === 'in' ? AVATAR('LF', 'Lucas Ferreira', 'sm', 'info') : ''}<div class="cn-stack" data-gap="1" data-align="${d === 'in' ? 'start' : 'end'}"><div class="cn-inbox__bubble">${t}</div><span class="cn-text-body-xs cn-app__muted">${time}</span></div></div>`).join('')}<div class="cn-inbox__bubble-row" data-direction="in">${AVATAR('LF', 'Lucas Ferreira', 'sm', 'info')}<div class="cn-inbox__bubble cn-inbox__typing" aria-label="Lucas is typing"><span></span><span></span><span></span></div></div></div><footer class="cn-inbox__composer"><div class="cn-row" data-gap="2"><div class="cn-input cn-flex-1" data-variant="default" data-size="md"><input class="cn-input__field" type="text" placeholder="Message Lucas…" aria-label="Message"></div>${BTN('primary', 'Send', 'md')}</div></footer></section></div>` },
    { title: 'Notification center', html: `<div class="cn-app">${SIDEBAR('Home')}<main class="cn-app__main">${PAGE_HEADER('Notifications', 'Everything that needs your attention, newest first.', `${BTN('link-color', 'Mark all as read', 'md')}${BTN('outline', 'Settings', 'md', ICON.settings)}`, 'simple')}${TABS(['All', 'Mentions', 'Assigned to you', 'Following'], 0)}<div class="cn-stack" data-gap="6" style="max-width:800px">${[['Today', [['MC', 'Maya Chen', 'mentioned you in', 'Q3 roadmap review', '9:41', true, 'accent'], ['DC', 'Daniel Costa', 'assigned you', 'Billing webhook retries', '8:20', true, 'success'], ['SA', 'Sofia Almeida', 'shared', 'Brand assets v3', '7:55', false, 'warning']]], ['Yesterday', [['LF', 'Lucas Ferreira', 'commented on', 'Drawer focus trap', '18:02', false, 'info'], ['AK', 'Aisha Khan', 'resolved', 'Webhook alert threshold', '16:40', false, 'accent'], ['NB', 'Noah Berg', 'requested review on', 'Onboarding copy', '11:15', false, 'success']]]].map(([day, items]) => `<section class="cn-stack" data-gap="2"><h2 class="cn-text-label-sm cn-app__muted">${day}</h2><div class="cn-card" data-variant="default" data-padding="none"><ul class="cn-list" data-density="default" data-variant="plain">${(items as (string | boolean)[][]).map(([i, n, a, tgt, t, unread, tone]) => `<li class="cn-list__item"${unread ? ' data-selected' : ''}><span class="cn-list__leading">${AVATAR(i as string, n as string, 'md', tone as string)}</span><span class="cn-list__content"><span class="cn-list__title"><strong>${n}</strong> ${a} <strong>${tgt}</strong></span><span class="cn-list__description">${t}</span></span><span class="cn-list__trailing">${unread ? '<span class="cn-inbox__dot" aria-label="Unread"></span>' : ''}${BTN('ghost', 'View', 'sm')}</span></li>`).join('')}</ul></div></section>`).join('')}</div></main></div>` },
  ],
  css: `${APP_CSS}
.cn-inbox__list { width: 360px; flex-shrink: 0; display: flex; flex-direction: column; border-inline-end: {border.width.thin} solid {color.border-default}; background-color: {color.bg-surface}; min-height: 720px; }
.cn-inbox__list-head { display: flex; flex-direction: column; gap: {space.3}; padding: {space.5} {space.4} {space.3}; border-bottom: {border.width.thin} solid {color.border-default}; }
.cn-inbox__threads { display: flex; flex-direction: column; overflow: auto; }
.cn-inbox__thread { display: flex; gap: {space.3}; padding: {space.4}; border-bottom: {border.width.thin} solid {color.border-subtle}; text-decoration: none; color: inherit; }
.cn-inbox__thread:hover { background-color: {color.bg-subtle}; }
.cn-inbox__thread--active { background-color: {color.bg-subtle}; box-shadow: inset 2px 0 0 {color.bg-action}; }
.cn-inbox__thread[data-unread] .cn-inbox__name { font-weight: {font.weight.semibold}; }
.cn-inbox__thread[data-unread] .cn-inbox__name::after { content: ""; display: inline-block; width: 8px; height: 8px; border-radius: {radius.full}; background-color: {color.bg-action}; margin-inline-start: {space.2}; vertical-align: middle; }
.cn-inbox__thread-body { display: flex; flex-direction: column; gap: {space.0.5}; min-width: 0; flex: 1 1 auto; }
.cn-inbox__subject { color: {color.fg-default}; overflow: hidden; text-overflow: ellipsis; white-space: nowrap; }
.cn-inbox__preview { overflow: hidden; text-overflow: ellipsis; white-space: nowrap; }
.cn-inbox__reading { flex: 1 1 auto; min-width: 0; display: flex; flex-direction: column; background-color: {color.bg-surface}; }
.cn-inbox__reading-head { display: flex; justify-content: space-between; align-items: flex-start; gap: {space.4}; padding: {space.5} {space.6}; border-bottom: {border.width.thin} solid {color.border-default}; }
.cn-inbox__messages { display: flex; flex-direction: column; gap: {space.6}; padding: {space.6}; flex: 1 1 auto; overflow: auto; }
.cn-inbox__msg { display: flex; flex-direction: column; gap: {space.3}; }
.cn-inbox__msg-body { padding-inline-start: 52px; color: {color.fg-muted}; display: flex; flex-direction: column; gap: {space.4}; }
.cn-inbox__msg-body p { margin: 0; }
.cn-inbox__composer { display: flex; flex-direction: column; gap: {space.3}; padding: {space.4} {space.6}; border-top: {border.width.thin} solid {color.border-default}; background-color: {color.bg-surface}; }
.cn-inbox__chat { display: flex; flex-direction: column; gap: {space.4}; padding: {space.6}; flex: 1 1 auto; }
.cn-inbox__day { display: flex; justify-content: center; }
.cn-inbox__day span { font-size: {font.size.xs}; font-weight: {font.weight.medium}; color: {color.fg-subtle}; background-color: {color.bg-subtle}; border-radius: {radius.full}; padding: {space.1} {space.3}; }
.cn-inbox__bubble-row { display: flex; gap: {space.3}; align-items: flex-end; }
.cn-inbox__bubble-row[data-direction="out"] { justify-content: flex-end; }
.cn-inbox__bubble { max-width: 70%; padding: {space.2.5} {space.3.5}; border-radius: {radius.lg}; background-color: {color.bg-subtle}; color: {color.fg-default}; font-size: {font.size.md}; line-height: {font.lineHeight.normal}; border-start-start-radius: {radius.xs}; }
.cn-inbox__bubble-row[data-direction="out"] .cn-inbox__bubble { background-color: {color.bg-action}; color: {color.fg-on-action}; border-start-start-radius: {radius.lg}; border-start-end-radius: {radius.xs}; }
.cn-inbox__typing { display: inline-flex; gap: 4px; padding: {space.3} {space.3.5}; }
.cn-inbox__typing span { width: 6px; height: 6px; border-radius: {radius.full}; background-color: {color.fg-subtle}; animation: cn-inbox-typing 1.2s infinite ease-in-out; }
.cn-inbox__typing span:nth-child(2) { animation-delay: .2s; } .cn-inbox__typing span:nth-child(3) { animation-delay: .4s; }
@keyframes cn-inbox-typing { 0%, 60%, 100% { transform: translateY(0); opacity: .5; } 30% { transform: translateY(-3px); opacity: 1; } }
.cn-inbox__dot { display: inline-block; width: 8px; height: 8px; border-radius: {radius.full}; background-color: {color.bg-action}; margin-inline-end: {space.2}; }
@media (max-width: {breakpoint.lg}) { .cn-inbox__list { width: 100%; border: 0; } .cn-inbox__reading { display: none; } }`,
  viewport: 'desktop',
};
