import type { Pattern } from '../types.ts';
import { SIDEBAR, PAGE_HEADER, BTN, TEAM_TABLE, PAGINATION, BADGE, CARD_HEAD, ICON, APP_CSS, AVATAR, TABS, PEOPLE } from './_app.ts';

const FILTERS = `<div class="cn-row" data-justify="between" data-gap="3" data-wrap><div class="cn-row" data-gap="3">${TABS(['View all', 'Active', 'Invited', 'Offline'], 0, 'pill')}</div><div class="cn-row" data-gap="3"><div class="cn-input" data-variant="default" data-size="md" style="width:320px">${ICON.search.replace('cn-icon', 'cn-input__icon')}<input class="cn-input__field" type="search" placeholder="Search" aria-label="Search members"></div>${BTN('outline', 'Filters', 'md', ICON.menu)}</div></div>`;
const DRAWER = `<aside class="cn-app__drawer" aria-label="Member details"><div class="cn-app__drawer-head"><div class="cn-row" data-gap="4">${AVATAR('DC', 'Daniel Costa', 'xl', 'success', 'online')}<div class="cn-stack" data-gap="1"><span class="cn-text-heading-sm">Daniel Costa</span><span class="cn-text-body-md cn-app__muted">daniel@lumen.co</span><div class="cn-row" data-gap="1">${BADGE('Active', 'success', 'soft', true)}${BADGE('Engineering', 'info')}</div></div></div><button type="button" class="cn-close-button" data-size="sm" data-theme="light" aria-label="Close">${ICON.x.replace('cn-icon', 'cn-close-button__icon')}</button></div><div class="cn-app__drawer-body">${TABS(['Details', 'Activity', 'Permissions'], 0)}<dl class="cn-app__dl"><div><dt>Role</dt><dd>Engineering Manager</dd></div><div><dt>Teams</dt><dd>Platform, Billing, Design systems</dd></div><div><dt>Location</dt><dd>Lisbon, Portugal · GMT+1</dd></div><div><dt>Joined</dt><dd>12 March 2024</dd></div><div><dt>Last active</dt><dd>2 minutes ago</dd></div></dl><div class="cn-alert" data-tone="warning" data-variant="soft" data-layout="inline" role="status"><span class="cn-alert__icon" aria-hidden="true">${ICON.warning}</span><div class="cn-alert__content"><div class="cn-alert__title">Two-factor authentication is off</div><p class="cn-alert__description">Ask Daniel to enable it in Settings → Security.</p></div></div></div><div class="cn-app__drawer-foot">${BTN('outline', 'Remove from team', 'md')}${BTN('primary', 'Edit member', 'md')}</div></aside>`;

export const listDetailPage: Pattern = {
  name: 'List with detail drawer',
  slug: 'list-detail-page',
  category: 'app-page',
  description: 'The workhorse app page: a filterable table of records with a detail drawer that opens over the list instead of navigating away. Also as a card list and as a kanban board.',
  rules: [
    'Filters row above the table: view tabs (pill) on the left, search (320px) and a Filters button on the right.',
    'The table lives in a card with its header (title + count badge + actions) and a pagination footer.',
    'Selecting a row opens the 440px drawer on the right: header with avatar/title/status and a close button, tabs, a definition list, contextual alerts, and footer actions. The list stays visible and the selected row keeps its highlight.',
    'Never navigate to a separate page for one record; only deep edits open a dialog or a full page.',
    'Empty results show the EmptyState inside the table card, keeping the filters visible.',
  ],
  html: `<div class="cn-app">${SIDEBAR('Users')}<main class="cn-app__main">${PAGE_HEADER('Users', 'Manage the people in your workspace and their permissions.', `${BTN('outline', 'Import', 'md', ICON.copy)}${BTN('primary', 'Invite user', 'md', ICON.plus)}`)}${FILTERS}<section class="cn-card cn-app__table-card" data-variant="default" data-padding="none"><div class="cn-section-header" data-variant="card" data-divider="yes">${CARD_HEAD('All users', '', '', BDG())}</div><div class="cn-card__body cn-app__card-body cn-app__card-body--flush" role="region" tabindex="0" aria-label="Scrollable table">${TEAM_TABLE()}</div><footer class="cn-card__footer">${PAGINATION}</footer></section></main>${DRAWER}</div>`,
  variants: [
    { title: 'Card list with empty state', html: `<div class="cn-app">${SIDEBAR('Projects')}<main class="cn-app__main">${PAGE_HEADER('Integrations', 'Connect the tools your team already uses.', BTN('primary', 'Request integration', 'md'))}${FILTERS}<div class="cn-grid" data-cols="3" data-gap="6">${[['Slack', 'Send notifications to channels.', true], ['GitHub', 'Link pull requests to tasks.', true], ['Figma', 'Embed live design files.', false], ['Linear', 'Sync issues both ways.', false], ['Notion', 'Attach docs to projects.', true], ['Zapier', 'Automate anything else.', false]].map(([n, d, on]) => `<section class="cn-card" data-variant="default" data-padding="md"><div class="cn-card__body cn-stack" data-gap="4"><div class="cn-row" data-justify="between" data-align="start"><span class="cn-featured-icon" data-theme="modern" data-tone="gray" data-size="md" data-shape="square">${ICON.copy.replace('cn-icon', 'cn-featured-icon__icon')}</span><label class="cn-switch" data-size="sm"><input class="cn-switch__input" type="checkbox" role="switch"${on ? ' checked' : ''} aria-label="Enable ${n}"><span class="cn-switch__track" aria-hidden="true"><span class="cn-switch__thumb"></span></span></label></div><div class="cn-stack" data-gap="1"><span class="cn-text-heading-xs">${n}</span><span class="cn-text-body-sm cn-app__muted">${d}</span></div></div><footer class="cn-card__footer">${BTN('link-color', 'View integration', 'sm')}</footer></section>`).join('')}</div><section class="cn-card" data-variant="default" data-padding="none"><div class="cn-card__body"><div class="cn-empty-state" data-size="md" data-variant="default"><svg class="cn-empty-state__icon" viewBox="0 0 16 16" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" aria-hidden="true"><circle cx="7" cy="7" r="4.5"/><path d="M10.5 10.5L14 14"/></svg><h3 class="cn-empty-state__title">No integrations found</h3><p class="cn-empty-state__description">Your search “calendar” did not match any integration. Try another term or request one.</p><div class="cn-empty-state__actions">${BTN('outline', 'Clear search', 'md')}${BTN('primary', 'Request integration', 'md')}</div></div></div></section></main></div>` },
    { title: 'Kanban board', html: `<div class="cn-app">${SIDEBAR('Tasks')}<main class="cn-app__main">${PAGE_HEADER('Tasks', 'What the team is working on this sprint.', `${BTN('outline', 'Filters', 'md', ICON.menu)}${BTN('primary', 'New task', 'md', ICON.plus)}`)}<div class="cn-kanban" data-density="default">${[['To do', 'you', 4], ['In progress', 'agent', 3], ['In review', 'action', 2], ['Done', 'you', 5]].map(([col, owner, n], ci) => `<div class="cn-kanban__column" data-owner="${owner}"><div class="cn-kanban__column-header"><span class="cn-kanban__column-title">${col}</span><span class="cn-kanban__column-count">${n}</span></div><div class="cn-kanban__column-body">${Array.from({ length: Math.min(3, n as number) }, (_, i) => `<article class="cn-kanban__card"><span class="cn-kanban__card-title">${['Design settings page', 'Fix billing webhook', 'Write onboarding copy', 'QA mobile drawer', 'Ship dark mode'][(ci + i) % 5]}</span><div class="cn-kanban__card-meta">${BADGE(['Design', 'Bug', 'Content', 'QA', 'Feature'][(ci + i) % 5], ['accent', 'danger', 'info', 'warning', 'success'][(ci + i) % 5])}<span>Sep ${12 + i}</span></div><div class="cn-kanban__card-footer">${AVATAR(PEOPLE[(ci + i) % 6][0], PEOPLE[(ci + i) % 6][1], 'xs', PEOPLE[(ci + i) % 6][4])}<span class="cn-text-body-xs cn-app__muted">${2 + i} comments</span></div></article>`).join('')}</div></div>`).join('')}</div></main></div>` },
  ],
  css: APP_CSS,
  viewport: 'desktop',
};
function BDG() { return BADGE('240 users', 'accent'); }
