import type { Pattern } from '../types.ts';
import { BTN, AVATAR, BADGE, ICON, APP_CSS, STAT, FIELD, INPUT } from './_app.ts';

const PHONE = (title: string, body: string, tab = 0, back = false, action = '') => `<div class="cn-phone"><header class="cn-phone__bar">${back ? `<button type="button" class="cn-icon-button" data-variant="ghost" data-size="md" data-shape="square" aria-label="Back">${ICON.chevronRight.replace('cn-icon', 'cn-icon-button__icon').replace('<svg', '<svg style="transform:rotate(180deg)"')}</button>` : `<span class="cn-phone__logo" aria-hidden="true"></span>`}<span class="cn-text-label-md cn-phone__title">${title}</span>${action || `<button type="button" class="cn-icon-button" data-variant="ghost" data-size="md" data-shape="square" aria-label="Notifications">${ICON.inbox.replace('cn-icon', 'cn-icon-button__icon')}</button>`}</header><main class="cn-phone__body">${body}</main><nav class="cn-phone__tabs" aria-label="Main">${[['Home', ICON.home], ['Tasks', ICON.check], ['Inbox', ICON.inbox], ['Profile', ICON.user]].map(([l, i], k) => `<a href="#" class="cn-phone__tab"${k === tab ? ' aria-current="page"' : ''}>${i}<span>${l}</span></a>`).join('')}</nav></div>`;
const ITEM = (i: string, n: string, tone: string, t: string, d: string, badge = '') => `<li class="cn-list__item"><span class="cn-list__leading">${AVATAR(i, n, 'md', tone)}</span><span class="cn-list__content"><span class="cn-list__title">${t}</span><span class="cn-list__description">${d}</span></span><span class="cn-list__trailing">${badge}${ICON.chevronRight.replace('cn-icon', 'cn-list__chevron')}</span></li>`;

export const mobileApp: Pattern = {
  name: 'Phone app screens',
  slug: 'mobile-app',
  category: 'app-page',
  description: 'The application at 375px: top bar + content + bottom tab bar. Home with stats and a list, a searchable list with filter chips, a detail screen with a sticky action, a form, and a bottom sheet.',
  rules: [
    'Shell: 56px top bar (back or logo, centered title, one icon action), scrolling content with 16px side padding, 64px bottom tab bar with 4–5 items (icon 24 + label 11px); the current tab is brand-colored.',
    'Controls are lg (44px) on phones; primary actions sit in a sticky footer above the tab bar, full width.',
    'Lists are edge-to-edge rows (56px) with avatar, title, one-line description and a chevron; cards only for grouped content.',
    'Filters are horizontal scrolling chips under the search field; never a sidebar or a dropdown filter panel.',
    'Detail screens open as pushed pages (back arrow), quick edits as bottom sheets (drawer side=bottom) with a grab handle.',
    'Everything here is the same components as desktop with data-size="lg"; no separate mobile component set.',
  ],
  html: PHONE('Home', `<div class="cn-stack" data-gap="5" style="padding:var(--cn-space-4)"><div class="cn-stack" data-gap="1"><span class="cn-text-body-sm cn-app__muted">Good morning</span><h1 class="cn-text-heading-md">Maya Chen</h1></div><div class="cn-grid" data-cols="2" data-gap="3" data-keep>${STAT('Open tasks', '9', '−2', 'down', 'This week')}${STAT('Waiting on you', '3', '+1', 'up', 'Reviews')}</div><div class="cn-row" data-justify="between"><h2 class="cn-text-heading-xs">Needs your attention</h2>${BTN('link-color', 'See all', 'sm')}</div></div><ul class="cn-list" data-density="default" data-variant="plain">${ITEM('DC', 'Daniel Costa', 'success', 'Approve billing refactor', 'PR #482 · waiting 2h', BADGE('Review', 'warning'))}${ITEM('SA', 'Sofia Almeida', 'warning', 'Brand assets v3', 'Shared 3 files', BADGE('New', 'info'))}${ITEM('LF', 'Lucas Ferreira', 'info', 'Drawer focus trap', 'Assigned to you', BADGE('Bug', 'danger'))}${ITEM('NB', 'Noah Berg', 'success', 'Onboarding copy', 'Comment · 1h', '')}</ul>`, 0),
  variants: [
    { title: 'Searchable list with filter chips', html: PHONE('Users', `<div class="cn-stack" data-gap="3" style="padding:var(--cn-space-4) var(--cn-space-4) 0"><div class="cn-input" data-variant="default" data-size="lg">${ICON.search.replace('cn-icon', 'cn-input__icon')}<input class="cn-input__field" type="search" placeholder="Search people" aria-label="Search people"></div><div class="cn-phone__chips">${['All', 'Active', 'Admins', 'Invited', 'Offline'].map((c, i) => `<button type="button" class="cn-tag" data-tone="${i === 1 ? 'accent' : 'neutral'}" data-variant="outline" data-size="md" aria-pressed="${i === 1}"><span class="cn-tag__label">${c}</span></button>`).join('')}</div><span class="cn-text-body-sm cn-app__muted">198 active</span></div><ul class="cn-list" data-density="default" data-variant="plain">${[['MC', 'Maya Chen', 'accent', 'Product Manager'], ['DC', 'Daniel Costa', 'success', 'Engineering Manager'], ['SA', 'Sofia Almeida', 'warning', 'Design'], ['LF', 'Lucas Ferreira', 'info', 'Frontend'], ['AK', 'Aisha Khan', 'accent', 'Backend'], ['NB', 'Noah Berg', 'success', 'Product Design'], ['ER', 'Elena Rossi', 'warning', 'UX Design']].map(([i, n, tone, r]) => ITEM(i, n, tone, n, r, BADGE('Active', 'success', 'soft', true))).join('')}</ul>`, 3) },
    { title: 'Detail with sticky action', html: PHONE('Task', `<div class="cn-stack" data-gap="5" style="padding:var(--cn-space-4)"><div class="cn-row" data-gap="2">${BADGE('Bug', 'danger')}${BADGE('In progress', 'accent', 'soft', true)}</div><h1 class="cn-text-heading-md">Drawer focus trap escapes on last button</h1><p class="cn-text-body-md cn-app__muted">Focus leaves the drawer when tabbing from the footer buttons because they render outside the trap wrapper. Reproduces on Safari and Chrome.</p><dl class="cn-app__dl"><div><dt>Assignee</dt><dd><div class="cn-row" data-gap="2">${AVATAR('LF', 'Lucas Ferreira', 'xs', 'info')}<span>Lucas Ferreira</span></div></dd></div><div><dt>Due</dt><dd>Fri, 12 Sep</dd></div><div><dt>Project</dt><dd>Design system</dd></div></dl><div class="cn-stack" data-gap="2"><h2 class="cn-text-heading-xs">Activity</h2><ul class="cn-list" data-density="compact" data-variant="plain">${[['LF', 'Lucas Ferreira', 'info', 'moved to In progress', '10:16'], ['MC', 'Maya Chen', 'accent', 'commented: “Nice catch.”', '10:14']].map(([i, n, tone, a, t]) => `<li class="cn-list__item"><span class="cn-list__leading">${AVATAR(i, n, 'sm', tone)}</span><span class="cn-list__content"><span class="cn-list__title">${n}</span><span class="cn-list__description">${a}</span></span><span class="cn-list__trailing">${t}</span></li>`).join('')}</ul></div></div><footer class="cn-phone__sticky">${BTN('outline', 'Comment', 'lg')}${BTN('primary', 'Mark done', 'lg')}</footer>`, 1, true, `<button type="button" class="cn-icon-button" data-variant="ghost" data-size="md" data-shape="square" aria-label="More">${ICON.dots.replace('cn-icon', 'cn-icon-button__icon')}</button>`) },
    { title: 'Form', html: PHONE('New task', `<form class="cn-stack" data-gap="5" style="padding:var(--cn-space-4)">${FIELD('m-title', 'Title', INPUT('m-title', '', 'text', 'What needs to be done?').replace('data-size="md"', 'data-size="lg"'))}${FIELD('m-desc', 'Description', `<div class="cn-textarea" data-size="lg" data-resize="none"><textarea class="cn-textarea__field" id="m-desc" rows="4" placeholder="Add details…"></textarea></div>`)}${FIELD('m-proj', 'Project', `<div class="cn-select" data-variant="default" data-size="lg"><select class="cn-select__field" id="m-proj" aria-label="Project"><option>Design system</option><option>Billing platform</option><option>Website redesign</option></select><svg class="cn-select__chevron" viewBox="0 0 16 16" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="M4 6l4 4 4-4"/></svg></div>`)}${FIELD('m-due', 'Due date', INPUT('m-due', '', 'date').replace('data-size="md"', 'data-size="lg"'))}<label class="cn-switch" data-size="md"><input class="cn-switch__input" type="checkbox" role="switch" checked><span class="cn-switch__track" aria-hidden="true"><span class="cn-switch__thumb"></span></span><span class="cn-switch__label">Notify assignee</span></label></form><footer class="cn-phone__sticky">${BTN('primary', 'Create task', 'lg')}</footer>`, 1, true, '<span style="width:44px"></span>') },
    { title: 'Bottom sheet over a list', html: `<div class="cn-phone cn-phone--sheet">${PHONE('Users', `<ul class="cn-list" data-density="default" data-variant="plain">${[['MC', 'Maya Chen', 'accent', 'Product Manager'], ['DC', 'Daniel Costa', 'success', 'Engineering Manager'], ['SA', 'Sofia Almeida', 'warning', 'Design'], ['LF', 'Lucas Ferreira', 'info', 'Frontend'], ['AK', 'Aisha Khan', 'accent', 'Backend']].map(([i, n, tone, r]) => ITEM(i, n, tone, n, r)).join('')}</ul>`, 3).replace('class="cn-phone"', 'class="cn-phone__inner"')}<div class="cn-phone__scrim"></div><div class="cn-phone__sheet" role="dialog" aria-modal="true" aria-label="Daniel Costa"><span class="cn-phone__handle" aria-hidden="true"></span><div class="cn-row" data-gap="3" style="padding:var(--cn-space-2) var(--cn-space-4) var(--cn-space-4)">${AVATAR('DC', 'Daniel Costa', 'lg', 'success', 'online')}<div class="cn-stack" data-gap="0"><span class="cn-text-heading-xs">Daniel Costa</span><span class="cn-text-body-sm cn-app__muted">Engineering Manager · Online</span></div></div><ul class="cn-list" data-density="default" data-variant="plain">${[['Message', ICON.inbox], ['Call', ICON.user], ['View profile', ICON.external], ['Remove from team', ICON.trash]].map(([l, i], k) => `<li class="cn-list__item${k === 3 ? ' cn-phone__danger' : ''}"><span class="cn-list__leading">${i}</span><span class="cn-list__content"><span class="cn-list__title">${l}</span></span></li>`).join('')}</ul><div style="padding:var(--cn-space-4)">${BTN('outline', 'Cancel', 'lg').replace('class="cn-button"', 'class="cn-button" style="width:100%"')}</div></div></div>` },
  ],
  css: `${APP_CSS}
.cn-phone { width: 375px; max-width: 100%; min-height: 720px; margin-inline: auto; background-color: {color.bg-surface}; display: flex; flex-direction: column; position: relative; overflow: hidden; border-inline: {border.width.thin} solid {color.border-default}; }
.cn-phone__bar { display: flex; align-items: center; gap: {space.2}; height: 56px; padding-inline: {space.3}; border-bottom: {border.width.thin} solid {color.border-default}; background-color: {color.bg-surface}; position: sticky; top: 0; z-index: {z.sticky}; }
.cn-phone__title { flex: 1 1 auto; text-align: center; }
.cn-phone__logo { width: 28px; height: 28px; border-radius: {radius.md}; background-color: {color.bg-action}; margin-inline: {space.2}; }
.cn-phone__body { flex: 1 1 auto; overflow: auto; display: flex; flex-direction: column; background-color: {color.bg-canvas}; }
.cn-phone__body .cn-list { background-color: {color.bg-surface}; }
.cn-phone__tabs { display: grid; grid-auto-flow: column; grid-auto-columns: 1fr; height: 64px; border-top: {border.width.thin} solid {color.border-default}; background-color: {color.bg-surface}; }
.cn-phone__tab { display: flex; flex-direction: column; align-items: center; justify-content: center; gap: 2px; font-size: 11px; font-weight: {font.weight.medium}; color: {color.fg-subtle}; text-decoration: none; }
.cn-phone__tab .cn-icon { width: 24px; height: 24px; }
.cn-phone__tab[aria-current="page"] { color: {color.fg-action}; }
.cn-phone__chips { display: flex; gap: {space.2}; overflow-x: auto; padding-bottom: {space.1}; scrollbar-width: none; }
.cn-phone__sticky { position: sticky; bottom: 0; display: flex; gap: {space.3}; padding: {space.3} {space.4}; background-color: {color.bg-surface}; border-top: {border.width.thin} solid {color.border-default}; margin-top: auto; }
.cn-phone__sticky .cn-button { flex: 1 1 0; }
.cn-phone--sheet { background: none; border: 0; }
.cn-phone__inner { width: 100%; min-height: 720px; background-color: {color.bg-surface}; display: flex; flex-direction: column; border-inline: {border.width.thin} solid {color.border-default}; }
.cn-phone__scrim { position: absolute; inset: 0; background-color: {color.bg-overlay}; }
.cn-phone__sheet { position: absolute; left: 0; right: 0; bottom: 0; background-color: {color.bg-surface-raised}; border-start-start-radius: {radius.2xl}; border-start-end-radius: {radius.2xl}; box-shadow: {shadow.xl}; padding-top: {space.2}; }
.cn-phone__handle { display: block; width: 40px; height: 4px; border-radius: {radius.full}; background-color: {color.bg-muted}; margin: 0 auto {space.2}; }
.cn-phone__danger .cn-list__title, .cn-phone__danger .cn-list__leading { color: {color.fg-danger}; }
.cn-phone .cn-list__leading .cn-icon { width: 20px; height: 20px; color: {color.fg-muted}; }`,
  viewport: 'mobile',
};
