import type { Pattern } from '../types.ts';
import { SIDEBAR, PAGE_HEADER, BTN, ICON, APP_CSS, FIELD, INPUT, TEAM_TABLE, CARD_HEAD, BADGE, AVATAR } from './_app.ts';

const PAGE = `<div class="cn-app cn-modal-flow__page" aria-hidden="true">${SIDEBAR('Users')}<main class="cn-app__main">${PAGE_HEADER('Users', 'Manage the people in your workspace.', BTN('primary', 'Invite user', 'md', ICON.plus))}<section class="cn-card cn-app__table-card" data-variant="default" data-padding="none"><div class="cn-section-header" data-variant="card" data-divider="yes">${CARD_HEAD('All users', '', '', BADGE('240 users', 'accent'))}</div><div class="cn-card__body cn-app__card-body cn-app__card-body--flush" role="region" tabindex="0" aria-label="Scrollable table">${TEAM_TABLE()}</div></section></main></div>`;
const OVERLAY = (panel: string, align = 'center') => `<div class="cn-modal-flow">${PAGE}<div class="cn-modal-flow__backdrop" data-align="${align}">${panel}</div></div>`;
const DIALOG = (size: string, variant: string, icon: string, tone: string, title: string, desc: string, body: string, footer: string) => `<div class="cn-dialog" data-size="${size}" data-variant="${variant}" data-state="open" role="dialog" aria-modal="true" aria-labelledby="mf-title"><div class="cn-dialog__header"><div class="cn-stack" data-gap="4" data-align="start"><span class="cn-featured-icon" data-theme="outline" data-tone="${tone}" data-size="md" data-shape="circle">${icon.replace('cn-icon', 'cn-featured-icon__icon')}</span><div class="cn-stack" data-gap="1"><h2 class="cn-dialog__title" id="mf-title">${title}</h2><p class="cn-dialog__description">${desc}</p></div></div><button type="button" class="cn-dialog__close cn-close-button" data-size="md" data-theme="light" aria-label="Close">${ICON.x.replace('cn-icon', 'cn-close-button__icon')}</button></div>${body ? `<div class="cn-dialog__body">${body}</div>` : ''}<div class="cn-dialog__footer">${footer}</div></div>`;

export const modalFlows: Pattern = {
  name: 'Dialog and drawer flows',
  slug: 'modal-flows',
  category: 'app-page',
  description: 'Overlays in context: a destructive confirmation, a form dialog, a two-step dialog and an edit drawer, each rendered over the users page with the scrim.',
  rules: [
    'Confirmation dialogs (sm, 400px): outline featured icon (error for destructive), title heading-md, one sentence, footer with ghost Cancel + primary (danger for destructive); the destructive button names the action ("Delete user"), never "OK".',
    'Form dialogs (md, 480px): title + description, 1–4 fields (20px apart), footer Cancel + primary; longer forms use a drawer instead.',
    'Multi-step dialogs show a stepper or "Step 1 of 2" in the header and keep the same size across steps.',
    'Drawers (md, 480px) slide from the right for editing a record; the list stays visible behind the scrim.',
    'Focus is trapped, Escape closes, focus returns to the trigger; the page behind is aria-hidden.',
  ],
  html: OVERLAY(DIALOG('sm', 'destructive', ICON.trash, 'error', 'Delete user', 'Are you sure you want to delete Daniel Costa? This action cannot be undone.', '', `${BTN('outline', 'Cancel', 'lg')}${BTN('danger', 'Delete user', 'lg')}`)),
  variants: [
    { title: 'Form dialog (invite)', html: OVERLAY(DIALOG('md', 'default', ICON.user, 'brand', 'Invite team member', 'They’ll receive an email with a link to join Lumen.', `<form class="cn-stack" data-gap="5">${FIELD('mf-email', 'Email', INPUT('mf-email', '', 'email', 'name@company.com', ICON.inbox))}${FIELD('mf-role', 'Role', `<div class="cn-select" data-variant="default" data-size="md"><select class="cn-select__field" id="mf-role" aria-label="Role"><option>Member</option><option selected>Admin</option><option>Viewer</option></select><svg class="cn-select__chevron" viewBox="0 0 16 16" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="M4 6l4 4 4-4"/></svg></div>`, 'Admins can manage billing and members.')}<label class="cn-checkbox" data-size="md"><input class="cn-checkbox__input" type="checkbox" checked><span class="cn-checkbox__control" aria-hidden="true"><svg class="cn-checkbox__indicator" viewBox="0 0 16 16" fill="none" stroke="currentColor" stroke-width="1.75" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="M3 8.5l3 3 7-7"/></svg></span><span class="cn-checkbox__label">Send a welcome message</span></label></form>`, `${BTN('outline', 'Cancel', 'lg')}${BTN('primary', 'Send invite', 'lg')}`)) },
    { title: 'Two-step dialog (export)', html: OVERLAY(DIALOG('md', 'default', ICON.external, 'gray', 'Export users', 'Step 1 of 2 · Choose what to include.', `<div class="cn-stack" data-gap="3">${[['All users', '240 people, every column', true], ['Active users only', '198 people', false], ['Current selection', '1 person', false]].map(([t, d, on]) => `<label class="cn-radio cn-modal-flow__option" data-size="md"><input class="cn-radio__input" type="radio" name="mf-scope"${on ? ' checked' : ''}><span class="cn-radio__control" aria-hidden="true"><span class="cn-radio__indicator"></span></span><span class="cn-stack" data-gap="0"><span class="cn-radio__label">${t}</span><span class="cn-radio__description">${d}</span></span></label>`).join('')}</div>`, `${BTN('outline', 'Cancel', 'lg')}${BTN('primary', 'Continue', 'lg')}`)) },
    { title: 'Edit drawer over the list', html: OVERLAY(`<aside class="cn-drawer" data-side="right" data-size="md" data-state="open" role="dialog" aria-modal="true" aria-labelledby="mf-drawer-title"><div class="cn-drawer__header"><div class="cn-row" data-gap="3">${AVATAR('DC', 'Daniel Costa', 'lg', 'success')}<div class="cn-stack" data-gap="1"><h2 class="cn-drawer__title" id="mf-drawer-title">Edit member</h2><p class="cn-drawer__description">daniel@lumen.co</p></div></div><button type="button" class="cn-drawer__close cn-close-button" data-size="md" data-theme="light" aria-label="Close">${ICON.x.replace('cn-icon', 'cn-close-button__icon')}</button></div><div class="cn-drawer__body"><form class="cn-stack" data-gap="5">${FIELD('mf-name', 'Full name', INPUT('mf-name', 'Daniel Costa'))}${FIELD('mf-title', 'Title', INPUT('mf-title', 'Engineering Manager'))}${FIELD('mf-team', 'Teams', `<div class="cn-row" data-gap="2" data-wrap>${['Platform', 'Billing', 'Design systems'].map((t) => `<button type="button" class="cn-tag" data-tone="neutral" data-variant="outline" data-size="md" aria-pressed="true"><span class="cn-tag__label">${t}</span><span class="cn-tag__remove" role="button" aria-label="Remove ${t}">${ICON.x}</span></button>`).join('')}</div>`)}${FIELD('mf-access', 'Access', `<div class="cn-stack" data-gap="3">${['Can manage billing', 'Can invite members', 'Can delete projects'].map((l, i) => `<label class="cn-switch" data-size="sm"><input class="cn-switch__input" type="checkbox" role="switch"${i < 2 ? ' checked' : ''}><span class="cn-switch__track" aria-hidden="true"><span class="cn-switch__thumb"></span></span><span class="cn-switch__label">${l}</span></label>`).join('')}</div>`)}</form></div><div class="cn-drawer__footer">${BTN('danger-ghost', 'Remove member', 'md')}<span class="cn-flex-1"></span>${BTN('outline', 'Cancel', 'md')}${BTN('primary', 'Save changes', 'md')}</div></aside>`, 'end') },
  ],
  css: `${APP_CSS}
.cn-modal-flow { position: relative; min-height: 720px; overflow: hidden; }
.cn-modal-flow__page { pointer-events: none; }
.cn-modal-flow__backdrop { position: absolute; inset: 0; background-color: {color.bg-overlay}; display: flex; align-items: center; justify-content: center; padding: {space.6}; z-index: {z.modal}; }
.cn-modal-flow__backdrop[data-align="end"] { justify-content: flex-end; padding: 0; }
.cn-modal-flow__backdrop .cn-drawer { height: 100%; }
.cn-modal-flow__option { padding: {space.4}; border: {border.width.thin} solid {color.border-default}; border-radius: {radius.card}; }
.cn-modal-flow__option:has(:checked) { border-color: {color.border-action}; background-color: {color.bg-action-subtle}; }`,
  viewport: 'desktop',
};
