import type { Pattern } from '../types.ts';
import { BTN, FIELD, INPUT, ICON, APP_CSS, AVATAR } from './_app.ts';

const STEPS = (current: number) => `<ol class="cn-stepper" data-variant="number" aria-label="Setup progress" data-orientation="horizontal" data-size="md">${['Your details', 'Company', 'Invite team', 'Done'].map((s, i) => `<li class="cn-stepper__step" data-state="${i < current ? 'complete' : i === current ? 'current' : 'upcoming'}"${i === current ? ' aria-current="step"' : ''}><span class="cn-stepper__indicator">${i < current ? ICON.check.replace('cn-icon', 'cn-stepper__check') : i + 1}</span><span class="cn-stepper__content"><span class="cn-stepper__label">${s}</span></span>${i < 3 ? '<span class="cn-stepper__connector" aria-hidden="true"></span>' : ''}</li>`).join('')}</ol>`;
const LOGO = `<span class="cn-onb__logo" aria-hidden="true"></span>`;
const CARD = (title: string, text: string, body: string, step: number) => `<div class="cn-onb"><header class="cn-onb__head">${LOGO}<span class="cn-text-label-md">Lumen</span><span class="cn-text-body-sm cn-app__muted">Step ${step + 1} of 4</span></header><main class="cn-onb__main"><div class="cn-onb__card"><div class="cn-stack" data-gap="8">${STEPS(step)}<div class="cn-stack" data-gap="2"><h1 class="cn-text-heading-lg">${title}</h1><p class="cn-text-body-lg cn-app__muted">${text}</p></div>${body}</div></div></main></div>`;

export const onboardingPage: Pattern = {
  name: 'Onboarding wizard',
  slug: 'onboarding-page',
  category: 'app-page',
  description: 'First-run flow: a focused, single-column card with a step indicator, one question per step, a back/continue footer, and a finishing screen. Also as a split layout with a preview panel.',
  rules: [
    'No sidebar. A minimal header (logo, product name, "Step n of 4") and a centered 560px card with 32px padding.',
    'The stepper at the top of the card shows 3–5 steps: complete (check), current (brand), upcoming (muted); never more than 5.',
    'One question per step: heading-lg title, body-lg supporting text, then 1–4 fields (20px apart). Continue is the only primary button; Back is ghost on the left; "Skip for now" as a link when optional.',
    'Invite step: repeatable email rows with a role select and an "Add another" link button; the primary reads "Send invites".',
    'Finishing screen: success featured icon (outline circle), heading-lg, body-lg, one primary "Go to dashboard".',
  ],
  html: CARD('Tell us about you', 'This helps us personalize your workspace.', `<form class="cn-stack" data-gap="5">${FIELD('o-name', 'Full name', INPUT('o-name', 'Maya Chen'))}${FIELD('o-role', 'What best describes your role?', `<div class="cn-select" data-variant="default" data-size="md"><select class="cn-select__field" id="o-role" aria-label="Role"><option>Founder</option><option selected>Product</option><option>Design</option><option>Engineering</option></select><svg class="cn-select__chevron" viewBox="0 0 16 16" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="M4 6l4 4 4-4"/></svg></div>`)}${FIELD('o-team', 'Team size', `<div class="cn-segmented-control" data-size="md" data-variant="full" role="radiogroup" aria-label="Team size">${['Just me', '2–10', '11–50', '51+'].map((v, i) => `<button type="button" class="cn-segmented-control__item" role="radio" aria-checked="${i === 1}">${v}</button>`).join('')}</div>`)}<footer class="cn-onb__foot">${BTN('ghost', 'Back', 'lg')}${BTN('primary', 'Continue', 'lg')}</footer></form>`, 0),
  variants: [
    { title: 'Company step with logo upload', html: CARD('Set up your company', 'You can change these later in Settings.', `<form class="cn-stack" data-gap="5">${FIELD('o-company', 'Company name', INPUT('o-company', 'Lumen'))}${FIELD('o-url', 'Workspace URL', `<div class="cn-input" data-variant="default" data-size="md"><span class="cn-input__affix">app.lumen.co/</span><input class="cn-input__field" id="o-url" type="text" value="lumen"></div>`)}${FIELD('o-logo', 'Logo', `<div class="cn-row" data-gap="4"><span class="cn-avatar" data-size="xl" data-shape="square" data-tone="accent" data-status="none" role="img" aria-label="Logo preview"><span class="cn-avatar__fallback" aria-hidden="true">L</span></span><div class="cn-file-dropzone cn-flex-1" data-size="sm"><input class="cn-file-dropzone__input" type="file" aria-label="Upload logo"><span class="cn-file-dropzone__icon" aria-hidden="true">${ICON.copy}</span><span class="cn-file-dropzone__title"><strong>Click to upload</strong> or drag and drop</span><span class="cn-file-dropzone__hint">SVG or PNG, at least 256×256</span></div></div>`)}<footer class="cn-onb__foot">${BTN('ghost', 'Back', 'lg')}${BTN('primary', 'Continue', 'lg')}</footer></form>`, 1) },
    { title: 'Invite team', html: CARD('Invite your team', 'Add the people you work with. They’ll get an email with a link.', `<form class="cn-stack" data-gap="4">${['daniel@lumen.co', 'sofia@lumen.co', ''].map((e, i) => `<div class="cn-onb__invite"><div class="cn-input cn-flex-1" data-variant="default" data-size="md">${ICON.inbox.replace('cn-icon', 'cn-input__icon')}<input class="cn-input__field" type="email" value="${e}" placeholder="name@company.com" aria-label="Email ${i + 1}"></div><div class="cn-select" data-variant="default" data-size="md"><select class="cn-select__field" aria-label="Role ${i + 1}"><option>Member</option><option${i === 0 ? ' selected' : ''}>Admin</option></select><svg class="cn-select__chevron" viewBox="0 0 16 16" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="M4 6l4 4 4-4"/></svg></div></div>`).join('')}${BTN('link-color', '+ Add another', 'md')}<footer class="cn-onb__foot">${BTN('ghost', 'Back', 'lg')}<div class="cn-row" data-gap="3" data-wrap>${BTN('link', 'Skip for now', 'lg')}${BTN('primary', 'Send invites', 'lg')}</div></footer></form>`, 2) },
    { title: 'Done', html: `<div class="cn-onb"><header class="cn-onb__head">${LOGO}<span class="cn-text-label-md">Lumen</span><span class="cn-text-body-sm cn-app__muted">Step 4 of 4</span></header><main class="cn-onb__main"><div class="cn-onb__card cn-center"><div class="cn-stack cn-center" data-gap="6" data-align="center"><span class="cn-featured-icon" data-theme="outline" data-tone="success" data-size="lg" data-shape="circle">${ICON.check.replace('cn-icon', 'cn-featured-icon__icon')}</span><div class="cn-stack" data-gap="2"><h1 class="cn-text-heading-lg">You’re all set</h1><p class="cn-text-body-lg cn-app__muted">Your workspace is ready and 2 invites are on their way. You can add more people any time from Settings → Team.</p></div><div class="cn-row" data-gap="3" data-justify="center">${AVATAR('MC', 'Maya Chen', 'md', 'accent')}${AVATAR('DC', 'Daniel Costa', 'md', 'success')}${AVATAR('SA', 'Sofia Almeida', 'md', 'warning')}</div>${BTN('primary', 'Go to dashboard', 'lg')}</div></div></main></div>` },
    { title: 'Split with live preview', html: `<div class="cn-onb cn-onb--split"><div class="cn-onb__side"><header class="cn-onb__head">${LOGO}<span class="cn-text-label-md">Lumen</span></header><main class="cn-onb__main"><div class="cn-onb__card cn-onb__card--flush"><div class="cn-stack" data-gap="8">${STEPS(1)}<div class="cn-stack" data-gap="2"><h1 class="cn-text-heading-lg">Choose your brand color</h1><p class="cn-text-body-lg cn-app__muted">It’s used for buttons, links and highlights across the product.</p></div><div class="cn-row" data-gap="3" data-wrap>${['brand.600', 'blue.600', 'green.600', 'amber.600', 'red.600', 'neutral.900'].map((c, i) => `<button type="button" class="cn-onb__swatch" style="background:var(--cn-${c.replace('.', '-')})" aria-label="${c}" aria-pressed="${i === 0}"></button>`).join('')}</div><footer class="cn-onb__foot">${BTN('ghost', 'Back', 'lg')}${BTN('primary', 'Continue', 'lg')}</footer></div></div></main></div><aside class="cn-onb__preview" aria-label="Preview"><div class="cn-card" data-variant="default" data-padding="md" style="width:360px"><div class="cn-card__body cn-stack" data-gap="4"><div class="cn-row" data-gap="3">${AVATAR('MC', 'Maya Chen', 'md', 'accent')}<div class="cn-stack" data-gap="0"><span class="cn-text-label-sm">Maya Chen</span><span class="cn-text-body-sm cn-app__muted">Product Manager</span></div></div><p class="cn-text-body-md cn-app__muted">Your primary button, links and selected states will use the color you pick.</p><div class="cn-row" data-gap="2">${BTN('outline', 'Secondary', 'md')}${BTN('primary', 'Primary', 'md')}</div></div></div></aside></div>` },
  ],
  css: `${APP_CSS}
.cn-onb { min-height: 100vh; background-color: {color.bg-canvas}; display: flex; flex-direction: column; }
.cn-onb__head { display: flex; align-items: center; gap: {space.3}; height: 64px; padding-inline: {space.8}; }
.cn-onb__head > :last-child { margin-inline-start: auto; }
.cn-onb__logo { width: 32px; height: 32px; border-radius: {radius.lg}; background-color: {color.bg-action}; }
.cn-onb__main { flex: 1 1 auto; display: flex; align-items: flex-start; justify-content: center; padding: {space.10} {space.4} {space.16}; }
.cn-onb__card { width: 100%; max-width: 560px; background-color: {color.bg-surface}; border: {border.width.thin} solid {color.border-default}; border-radius: {radius.2xl}; padding: {space.8}; box-shadow: {shadow.xs}; }
.cn-onb__card--flush { border: 0; box-shadow: none; background: transparent; padding: 0; }
.cn-onb__foot { display: flex; flex-wrap: wrap; justify-content: space-between; align-items: center; gap: {space.3}; padding-top: {space.4}; border-top: {border.width.thin} solid {color.border-default}; margin-top: {space.2}; }
.cn-onb__invite { display: flex; gap: {space.3}; }
.cn-onb__invite > .cn-select { width: 140px; flex-shrink: 0; }
.cn-onb__swatch { width: 40px; height: 40px; border-radius: {radius.full}; border: 0; cursor: pointer; box-shadow: 0 0 0 2px {color.bg-surface}; }
.cn-onb__swatch[aria-pressed="true"] { box-shadow: 0 0 0 2px {color.bg-surface}, 0 0 0 4px {color.border-action}; }
.cn-onb--split { flex-direction: row; }
.cn-onb__side { flex: 1 1 50%; display: flex; flex-direction: column; }
.cn-onb__preview { flex: 1 1 50%; background-color: {color.bg-subtle}; display: flex; align-items: center; justify-content: center; padding: {space.16}; border-inline-start: {border.width.thin} solid {color.border-default}; }
@media (max-width: {breakpoint.md}) { .cn-onb--split { flex-direction: column; } .cn-onb__preview { display: none; } .cn-onb__card { padding: {space.5}; } .cn-onb__head { padding-inline: {space.4}; } .cn-onb__invite { flex-direction: column; } .cn-onb__invite > .cn-input { flex: none; } .cn-onb__invite > .cn-select { width: 100%; } }`,
  viewport: 'both',
};
