import type { Pattern } from '../types.ts';
import { SIDEBAR, PAGE_HEADER, BTN, AVATAR, BADGE, ICON, APP_CSS, TABS, CARD_HEAD, CHECKBOX } from './_app.ts';

const ROLES = ['Owner', 'Admin', 'Member', 'Viewer'];
const PERMS: [string, string, boolean[]][] = [['Workspace', 'Manage billing', [true, true, false, false]], ['Workspace', 'Invite and remove members', [true, true, false, false]], ['Workspace', 'Change roles', [true, false, false, false]], ['Projects', 'Create projects', [true, true, true, false]], ['Projects', 'Delete projects', [true, true, false, false]], ['Projects', 'Edit any task', [true, true, true, false]], ['Data', 'Export data', [true, true, false, false]], ['Data', 'View audit log', [true, true, false, false]], ['Integrations', 'Manage API keys', [true, true, false, false]], ['Integrations', 'Connect apps', [true, true, true, false]]];
let last = '';
const MATRIX = `<table class="cn-table cn-perm__table" data-density="compact" data-variant="default"><thead class="cn-table__head"><tr class="cn-table__row"><th class="cn-table__header-cell" scope="col">Permission</th>${ROLES.map((r) => `<th class="cn-table__header-cell" scope="col" data-align="center"><div class="cn-stack cn-center" data-gap="1" data-align="center"><span>${r}</span><span class="cn-text-body-xs cn-app__muted">${[1, 3, 14, 6][ROLES.indexOf(r)]} people</span></div></th>`).join('')}</tr></thead><tbody class="cn-table__body">${PERMS.map(([group, p, vals]) => { const head = group !== last ? `<tr class="cn-table__row cn-perm__group"><td class="cn-table__cell" colspan="5">${group}</td></tr>` : ''; last = group; return head + `<tr class="cn-table__row"><td class="cn-table__cell"><span class="cn-text-body-sm">${p}</span></td>${vals.map((v, i) => `<td class="cn-table__cell" data-align="center">${i === 0 ? `<span class="cn-perm__lock" aria-label="Always on">${ICON.check}</span>` : CHECKBOX(`${p} for ${ROLES[i]}`, v)}</td>`).join('')}</tr>`; }).join('')}</tbody></table>`;

export const permissionsPage: Pattern = {
  name: 'Roles and permissions',
  slug: 'permissions-page',
  category: 'app-page',
  description: 'A roles × permissions matrix with grouped rows, a role detail with its members, and an API keys page.',
  rules: [
    'Matrix: permissions as rows grouped by area (group rows in bg-subtle, label-xs), roles as columns with the member count under the name; cells are checkboxes, the Owner column is locked (check icon, no control).',
    'Changes are saved explicitly: a sticky footer with "Discard" and "Save changes" appears when anything changed.',
    'Role detail: description, members list (avatar, name, email, remove) and an "Add members" primary; deleting a role requires moving its members first.',
    'API keys: table with name, key prefix in code style, created, last used, and a Revoke ghost-danger action; new keys are shown once in a dialog with a copy button.',
  ],
  html: `<div class="cn-app">${SIDEBAR('Settings')}<main class="cn-app__main">${PAGE_HEADER('Roles and permissions', 'Control what each role can do across the workspace.', BTN('outline', 'New role', 'md', ICON.plus))}${TABS(['Permissions', 'Roles', 'API keys'], 0)}<section class="cn-card cn-app__table-card" data-variant="default" data-padding="none"><div class="cn-section-header" data-variant="card" data-divider="yes">${CARD_HEAD('Permission matrix', 'Owners always have every permission.', BTN('link-color', 'Learn about roles', 'sm'))}</div><div class="cn-card__body cn-app__card-body cn-app__card-body--flush" role="region" tabindex="0" aria-label="Scrollable table">${MATRIX}</div><footer class="cn-card__footer"><div class="cn-row" data-justify="between"><span class="cn-text-body-sm cn-app__muted">2 unsaved changes</span><div class="cn-row" data-gap="2">${BTN('outline', 'Discard', 'sm')}${BTN('primary', 'Save changes', 'sm')}</div></div></footer></section></main></div>`,
  variants: [
    { title: 'Role detail with members', html: `<div class="cn-app">${SIDEBAR('Settings')}<main class="cn-app__main">${PAGE_HEADER('Admin', 'Can manage members, billing and projects. Cannot change roles.', `${BTN('danger-outline', 'Delete role', 'md')}${BTN('primary', 'Add members', 'md', ICON.plus)}`, 'simple', `<div class="cn-page-header__crumbs"><nav class="cn-breadcrumb" data-size="sm" aria-label="Breadcrumb"><ol class="cn-breadcrumb__list"><li class="cn-breadcrumb__item"><a class="cn-breadcrumb__link" href="#">Roles</a></li><li class="cn-breadcrumb__separator" aria-hidden="true">${ICON.chevronRight}</li><li class="cn-breadcrumb__item"><span class="cn-breadcrumb__current" aria-current="page">Admin</span></li></ol></nav></div>`)}<div class="cn-grid" data-cols="3" data-gap="6"><section class="cn-card cn-app__span2 cn-app__table-card" data-variant="default" data-padding="none"><div class="cn-section-header" data-variant="card" data-divider="yes">${CARD_HEAD('Members', '', '', BADGE('3 people', 'accent'))}</div><div class="cn-card__body cn-app__card-body cn-app__card-body--flush" role="region" tabindex="0" aria-label="Role members"><ul class="cn-list cn-perm__members" data-density="default" data-variant="plain">${[['MC', 'Maya Chen', 'maya@lumen.co', 'accent'], ['AK', 'Aisha Khan', 'aisha@lumen.co', 'accent'], ['ER', 'Elena Rossi', 'elena@lumen.co', 'warning']].map(([i, n, e, tone]) => `<li class="cn-list__item"><span class="cn-list__leading">${AVATAR(i, n, 'md', tone)}</span><span class="cn-list__content"><span class="cn-list__title">${n}</span><span class="cn-list__description">${e}</span></span><span class="cn-list__trailing">${BTN('ghost', 'Change role', 'sm')}${BTN('danger-ghost', 'Remove', 'sm')}</span></li>`).join('')}</ul></div></section><section class="cn-card" data-variant="default" data-padding="none"><div class="cn-section-header" data-variant="card" data-divider="yes">${CARD_HEAD('Permissions', '')}</div><div class="cn-card__body cn-app__card-body"><ul class="cn-stack" data-gap="3">${PERMS.map(([g, p, v]) => `<li class="cn-row" data-gap="2" data-align="start"><span class="cn-perm__mini" data-on="${v[1]}" aria-hidden="true">${v[1] ? ICON.check : ICON.x}</span><span class="cn-text-body-sm${v[1] ? '' : ' cn-app__muted'}">${p}</span></li>`).join('')}</ul></div></section></div></main></div>` },
    { title: 'API keys', html: `<div class="cn-app">${SIDEBAR('Settings')}<main class="cn-app__main">${PAGE_HEADER('API keys', 'Keys give full access to your workspace’s API. Keep them secret.', BTN('primary', 'Create key', 'md', ICON.plus))}${TABS(['Permissions', 'Roles', 'API keys'], 2)}<div class="cn-alert" data-tone="info" data-variant="soft" data-layout="inline" role="status"><span class="cn-alert__icon" aria-hidden="true">${ICON.info}</span><div class="cn-alert__content"><div class="cn-alert__title">Keys rotate automatically every 90 days</div><p class="cn-alert__description">You’ll get an email 7 days before a rotation. Change the schedule in Security settings.</p></div></div><section class="cn-card cn-app__table-card" data-variant="default" data-padding="none"><div class="cn-card__body cn-app__card-body cn-app__card-body--flush" role="region" tabindex="0" aria-label="Scrollable table"><table class="cn-table" data-density="default" data-variant="default"><thead class="cn-table__head"><tr class="cn-table__row"><th class="cn-table__header-cell" scope="col">Name</th><th class="cn-table__header-cell" scope="col">Key</th><th class="cn-table__header-cell" scope="col">Created by</th><th class="cn-table__header-cell" scope="col">Last used</th><th class="cn-table__header-cell" scope="col"><span class="cn-sr-only">Actions</span></th></tr></thead><tbody class="cn-table__body">${[['Production', 'lum_live_…8f2a', 'DC', 'Daniel Costa', 'success', '2 minutes ago', 'Active', 'success'], ['Staging', 'lum_test_…c91d', 'AK', 'Aisha Khan', 'accent', 'Yesterday', 'Active', 'success'], ['Zapier import', 'lum_live_…41bb', 'MC', 'Maya Chen', 'accent', '34 days ago', 'Unused', 'warning'], ['Legacy CRM sync', 'lum_live_…0e77', 'LF', 'Lucas Ferreira', 'info', 'Never', 'Revoked', 'neutral']].map(([n, k, i, who, tone, used, st, stone]) => `<tr class="cn-table__row"><td class="cn-table__cell"><div class="cn-stack" data-gap="0"><span class="cn-text-label-sm">${n}</span>${BADGE(st, stone, 'soft', true)}</div></td><td class="cn-table__cell"><code class="cn-code cn-perm__key" data-variant="inline" data-size="sm">${k}</code></td><td class="cn-table__cell"><div class="cn-row" data-gap="2">${AVATAR(i, who, 'xs', tone)}<span>${who}</span></div></td><td class="cn-table__cell">${used}</td><td class="cn-table__cell cn-table__actions"><div class="cn-row" data-gap="1" data-justify="end">${BTN('ghost', 'Copy', 'sm')}${st === 'Revoked' ? BTN('ghost', 'Delete', 'sm') : BTN('danger-ghost', 'Revoke', 'sm')}</div></td></tr>`).join('')}</tbody></table></div></section></main></div>` },
  ],
  css: `${APP_CSS}
.cn-app__span2 { grid-column: span 2; min-width: 0; }
.cn-perm__group .cn-table__cell { background-color: {color.bg-subtle}; font-size: {font.size.xs}; font-weight: {font.weight.semibold}; color: {color.fg-muted}; padding-block: {space.2}; }
.cn-perm__table .cn-table__cell[data-align="center"], .cn-perm__table .cn-table__header-cell[data-align="center"] { text-align: center; }
.cn-perm__table .cn-checkbox { justify-content: center; }
.cn-perm__lock { display: inline-flex; align-items: center; justify-content: center; width: 20px; height: 20px; border-radius: {radius.sm}; background-color: {color.bg-muted}; color: {color.fg-muted}; }
.cn-perm__lock .cn-icon, .cn-perm__mini .cn-icon { width: 14px; height: 14px; }
.cn-perm__mini { display: inline-flex; align-items: center; justify-content: center; width: 20px; height: 20px; border-radius: {radius.full}; background-color: {color.bg-subtle}; color: {color.fg-subtle}; flex-shrink: 0; }
.cn-perm__mini[data-on="true"] { background-color: {color.bg-success-subtle}; color: {color.fg-success}; }
.cn-code.cn-perm__key { white-space: nowrap; overflow-wrap: normal; }
@media (max-width: {breakpoint.md}) {
  .cn-app__span2 { grid-column: auto; }
  .cn-list.cn-perm__members .cn-list__item { flex-wrap: wrap; }
  .cn-list.cn-perm__members .cn-list__trailing { flex-basis: 100%; justify-content: flex-start; }
}`,
  viewport: 'desktop',
};
