import type { Pattern } from '../types.ts';
import { SIDEBAR, PAGE_HEADER, BTN, TABS, FIELD, INPUT, TEAM_TABLE, PAGINATION, BADGE, CARD_HEAD, ICON, APP_CSS, CHECKBOX } from './_app.ts';

const row = (label: string, hint: string, control: string) => `<div class="cn-app__form-row"><div class="cn-app__form-label"><span>${label}</span><span>${hint}</span></div><div class="cn-stack" data-gap="4">${control}</div></div>`;
const HEADER = (tab: number) => `${PAGE_HEADER('Settings', 'Manage your account settings and preferences.', `${BTN('outline', 'Cancel', 'md')}${BTN('primary', 'Save changes', 'md')}`)}${TABS(['My details', 'Profile', 'Password', 'Team', 'Plan', 'Billing', 'Notifications', 'Integrations'], tab)}`;

export const settingsPage: Pattern = {
  name: 'Settings page',
  slug: 'settings-page',
  category: 'app-page',
  description: 'Account and workspace settings: page header + tabs, then sections laid out as label-column / control-column rows separated by hairlines, with the actions at the end. Variants: profile form, team, plan & billing, notifications.',
  rules: [
    'Tabs under the page header select the settings area; the content is a single 1024px-max column.',
    'Each setting is a row: left column 280px with a semibold label and a one-line hint; right column the control(s), max 512px. Rows separated by 20px padding and a hairline.',
    'Section header (heading-sm + description + actions) at the top of each area; the save actions repeat at the bottom of long forms.',
    'Destructive actions (delete account) sit in their own last section with a danger-outline button.',
    'Team: section header with count badge, a table with checkbox, avatar, status, role, email and actions, then pagination.',
  ],
  html: `<div class="cn-app">${SIDEBAR('Settings')}<main class="cn-app__main">${HEADER(1)}<div class="cn-stack" data-gap="0" style="max-width:1024px"><div class="cn-section-header" data-variant="default" data-divider="yes">${CARD_HEAD('Personal info', 'Update your photo and personal details here.', `${BTN('outline', 'Cancel', 'sm')}${BTN('primary', 'Save', 'sm')}`)}</div>${row('Name', 'Shown on your profile and in mentions.', `<div class="cn-grid" data-cols="2" data-gap="4" data-keep>${INPUT('s-first', 'Maya')}${INPUT('s-last', 'Chen')}</div>`)}${row('Email address', 'Used for sign-in and notifications.', INPUT('s-email', 'maya@lumen.co', 'email', '', ICON.inbox))}${row('Your photo', 'This will be displayed on your profile.', `<div class="cn-row" data-gap="5" data-align="start"><span class="cn-avatar" data-size="2xl" data-shape="circle" data-tone="accent" data-status="none" role="img" aria-label="Maya Chen"><span class="cn-avatar__fallback" aria-hidden="true">MC</span></span><div class="cn-file-dropzone cn-flex-1" data-size="sm"><input class="cn-file-dropzone__input" type="file" aria-label="Upload photo"><span class="cn-file-dropzone__icon" aria-hidden="true">${ICON.copy}</span><span class="cn-file-dropzone__title"><strong>Click to upload</strong> or drag and drop</span><span class="cn-file-dropzone__hint">SVG, PNG, JPG or GIF (max. 800×400px)</span></div></div>`)}${row('Role', 'Your title inside the workspace.', INPUT('s-role', 'Product Manager'))}${row('Country', 'Where you are based, for tax and time zone.', `<div class="cn-select" data-variant="default" data-size="md"><select class="cn-select__field" id="s-country" aria-label="Country"><option>Brazil</option><option selected>United States</option><option>Portugal</option></select><svg class="cn-select__chevron" viewBox="0 0 16 16" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="M4 6l4 4 4-4"/></svg></div>`)}${row('Bio', 'Write a short introduction.', `<div class="cn-textarea" data-size="md" data-resize="vertical"><textarea class="cn-textarea__field" rows="4" aria-label="Bio">I’m a product manager based in Florianópolis. I like building things that make people’s work easier.</textarea></div><span class="cn-text-body-sm cn-app__muted">275 characters left</span>`)}<div class="cn-app__form-actions">${BTN('outline', 'Cancel', 'md')}${BTN('primary', 'Save changes', 'md')}</div></div></main></div>`,
  variants: [
    { title: 'Team', html: `<div class="cn-app">${SIDEBAR('Settings')}<main class="cn-app__main">${HEADER(3)}<div class="cn-stack" data-gap="6"><div class="cn-section-header" data-variant="with-badge" data-divider="yes">${CARD_HEAD('Team members', 'Manage your team members and their account permissions here.', `${BTN('outline', 'Download CSV', 'md')}${BTN('primary', 'Add team member', 'md', ICON.plus)}`, BADGE('100 users', 'accent'))}</div><section class="cn-card cn-app__table-card" data-variant="default" data-padding="none"><div class="cn-card__body cn-app__card-body cn-app__card-body--flush" role="region" tabindex="0" aria-label="Scrollable table">${TEAM_TABLE()}</div><footer class="cn-card__footer">${PAGINATION}</footer></section></div></main></div>` },
    { title: 'Plan and billing', html: `<div class="cn-app">${SIDEBAR('Settings')}<main class="cn-app__main">${HEADER(4)}<div class="cn-stack" data-gap="8" style="max-width:1024px"><div class="cn-section-header" data-variant="default" data-divider="yes">${CARD_HEAD('Account plans', 'Pick an account plan that fits your workflow.', BTN('outline', 'Compare plans', 'sm'))}</div><div class="cn-grid" data-cols="3" data-gap="6">${[['Basic plan', '$10', 'Includes up to 10 users, 20GB individual data and access to all features.', false], ['Business plan', '$20', 'Includes up to 20 users, 40GB individual data and priority support.', true], ['Enterprise plan', '$40', 'Unlimited users, unlimited data and personalised service.', false]].map(([n, p, d, cur]) => `<section class="cn-card" data-variant="default" data-padding="md"${cur ? ' data-selected' : ''}><div class="cn-card__body cn-app__plan"><div class="cn-row" data-justify="between" data-align="start"><div class="cn-stack" data-gap="1"><span class="cn-text-heading-xs">${n}</span><span class="cn-text-body-sm cn-app__muted">${d}</span></div>${cur ? BADGE('Current', 'accent') : ''}</div><span class="cn-text-heading-lg">${p}<span class="cn-text-body-sm cn-app__muted"> per month</span></span>${cur ? BTN('outline', 'Manage plan', 'md') : BTN('primary', 'Upgrade', 'md')}</div></section>`).join('')}</div><div class="cn-section-header" data-variant="default" data-divider="yes">${CARD_HEAD('Billing and invoicing', 'Pick an account plan that fits your workflow.', `${BTN('outline', 'Download all', 'sm')}`)}</div><section class="cn-card cn-app__table-card" data-variant="default" data-padding="none"><div class="cn-card__body cn-app__card-body cn-app__card-body--flush" role="region" tabindex="0" aria-label="Scrollable table"><table class="cn-table" data-density="default" data-variant="default"><thead class="cn-table__head"><tr class="cn-table__row"><th class="cn-table__header-cell" scope="col">Invoice</th><th class="cn-table__header-cell" scope="col">Billing date</th><th class="cn-table__header-cell" scope="col">Status</th><th class="cn-table__header-cell" scope="col" data-align="right">Amount</th><th class="cn-table__header-cell" scope="col"><span class="cn-sr-only">Actions</span></th></tr></thead><tbody class="cn-table__body">${['Dec 2026', 'Nov 2026', 'Oct 2026', 'Sep 2026'].map((m, i) => `<tr class="cn-table__row"><td class="cn-table__cell"><span class="cn-text-label-sm">Invoice #${1084 - i} – ${m}</span></td><td class="cn-table__cell">${m}</td><td class="cn-table__cell">${BADGE('Paid', 'success', 'soft', true)}</td><td class="cn-table__cell" data-align="right">USD $20.00</td><td class="cn-table__cell cn-table__actions">${BTN('link-color', 'Download', 'sm')}</td></tr>`).join('')}</tbody></table></div></section></div></main></div>` },
    { title: 'Notifications', html: `<div class="cn-app">${SIDEBAR('Settings')}<main class="cn-app__main">${HEADER(6)}<div class="cn-stack" data-gap="0" style="max-width:1024px"><div class="cn-section-header" data-variant="default" data-divider="yes">${CARD_HEAD('Notification settings', 'We may still send you important notifications about your account outside of your notification settings.')}</div>${[['Comments', 'These are notifications for comments on your posts and replies to your comments.'], ['Tags', 'These are notifications for when someone tags you in a comment, post or story.'], ['Reminders', 'These are notifications to remind you of updates you might have missed.'], ['More activity about you', 'These are notifications for posts on your profile, likes and other reactions.']].map(([l, h]) => row(l, h, `<label class="cn-switch" data-size="sm"><input class="cn-switch__input" type="checkbox" role="switch" checked><span class="cn-switch__track" aria-hidden="true"><span class="cn-switch__thumb"></span></span><span class="cn-switch__label">Push</span></label><label class="cn-switch" data-size="sm"><input class="cn-switch__input" type="checkbox" role="switch" checked><span class="cn-switch__track" aria-hidden="true"><span class="cn-switch__thumb"></span></span><span class="cn-switch__label">Email</span></label><label class="cn-switch" data-size="sm"><input class="cn-switch__input" type="checkbox" role="switch"><span class="cn-switch__track" aria-hidden="true"><span class="cn-switch__thumb"></span></span><span class="cn-switch__label">SMS</span></label>`)).join('')}<div class="cn-app__form-row"><div class="cn-app__form-label"><span>Danger zone</span><span>Permanently delete your account and all data.</span></div><div class="cn-stack" data-gap="3" data-align="start">${CHECKBOX('I understand this cannot be undone')}${BTN('danger-outline', 'Delete account', 'md')}</div></div></div></main></div>` },
  ],
  css: APP_CSS,
  viewport: 'desktop',
};
